source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/BusinessValidation/Rules/TaxIndicatorMustNotChangeInUpdateRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/Model/Charge.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Mapping/ChangeOfChargesMapper.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/BusinessValidation/Rules/StartDateVr209ValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/BusinessValidation/Rules/TaxIndicatorMustNotChangeInUpdateRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/BusinessValidation/Rules/VatPayerMustNotChangeInUpdateRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/ChargeCommandValidatorTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/AutoMoqDataAttribute.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/InlineAutoMoqDataAttribute.cs
This PR adds unit tests of the few business validation rules already found in the Charges repository.
Hence, this PR is the foundation for unit tests of many more business validation rules that will be added in future PRs.
We have added the AutoMoqDataAttribute to be able to provide inline data in unit test theories along with AutoFixture fixtures.
=> Business validation unit tests

build/infrastructure/azfun-charges-chargecommandreceiver.tf
The purpose of this PR is to switch to basic tier for charge command receiver and have the function always be on.
In addition, added some whitespaces to align readability of sections.
=> Change charge command receiver in terraform to always be on

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeCommandReceiver/ChargeCommandEndpoint.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeCommandReceiver/Startup.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Messaging/CorrelationContext.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Messaging/ICorrelationContext.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Messaging/ServiceBusChannel.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageReceiver/ChargeHttpTrigger.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageReceiver/Startup.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Messaging/MockableServiceBusSender.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Messaging/ServiceBusChannelTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Messaging/TestableServiceBusChannel.cs
As part of moving towards using the GEH messaging library for communicating between components, this PR adds additional needed building blocks.
NOTE: It does not implement the full framework or utilize the new channel at this point, this will be added later.
The following changes is part of this PR:
* An implementation of a messaging Channel that utilize ServiceBus communication using the AMQP protocol (default protocol of the ServiceBusSender)
* A correlelation context abstraction that makes sure we can dependency inject correction IDs into technologies that specifically support it (like ServiceBus)
* Changed MessageReceiver to use the new correlation context
* Changed ChargeCommandReceiver to use the new correlation context
* Tests showing that the channel utilize the ServiceBusSender …
=> Enabler: ServiceBusChannel implementation

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/InputValidationRulesFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/VatClassificationValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/ValidationRuleIdentifier.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChangeOfCharges/Transaction/VatClassification.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/VatClassificationValidationRuleTests.cs
Added new VatClassification.Unknown as default value, added VR488 VatClassificationValidationRule.cs and unittests of that rule
Input Validation of VR488
- Only Vat classification allowed is D01 Vat or D02 NoVat
Unknown value added to VatClassification to avoid default values ending up as valid input
* #195
=> Input validation VR488 

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/InputValidationRulesFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/ResolutionTariffValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/ValidationRuleIdentifier.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChangeOfCharges/Transaction/Resolution.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ResolutionTariffValidationRuleTests.cs
Input Validation of VR505-1
- Resolution must be P1D OR PT1H OR PT15M when ChargeType is Tariff
Unknown value added to Resolution to avoid default values ending up as valid input
* #195
=> Input validation VR505-1

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/InputValidationRulesFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/ResolutionFeeValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/ValidationRuleIdentifier.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChangeOfCharges/Transaction/Resolution.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ResolutionFeeValidationRuleTests.cs
Input Validation of VR505-1
- Resolution must be P1D when ChargeType is Fee
Unknown value added to Resolution to avoid default values ending up as valid input
* #195
=> Validation rule VR505-2

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/InputValidationRulesFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/ResolutionSubscriptionValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/ValidationRuleIdentifier.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChangeOfCharges/Transaction/Resolution.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ResolutionSubscriptionValidationRuleTests.cs
Input Validation of VR505-3
Resolution must be P1M when ChargeType is Subscription
Unknown value added to Resolution to avoid default values ending up as valid input
* #195
=> Validation rule VR505-3

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ChargeCommandInputValidator.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/IInputValidationRulesFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/InputValidationRulesFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ChargeCommandInputValidatorTest.cs
Because of VR445, we need to be able to validate a unknown operation type, and pass along a rejection to the post office in the future.
* #193
=> Validate ChargeCommand with unknown OperationType

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/ChargeTypeIsKnownValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/OperationTypeValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/ProcessTypeIsKnownValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/BusinessReasonCodeMustBeUpdateChargeInformationTest.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ChargeTypeIsKnownValidationRuleTest.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ChargeTypeIsKnownValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/OperationTypeValidationRuleTest.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ProcessTypeIsKnownValidationRuleTests.cs
… inspected
We have a few rules which allowed false positive by supplying them with a int value other than the allowed or the unknown option. This PR will address this issue.
* #193
=> Rules changed that look'ed at target value to not be unknown.

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/Model/ChargePrice.cs
I have introduced a bug when I created the RetiredTime prop on ChargePrice. The name of the column in the database scheme was RetiredDateTime. 
* #202
=> ChargePrice RetiredTime renamed to RetiredDateTime

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Acknowledgements/ChargeConfirmation.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Acknowledgements/ChargeRejection.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Application/ChangeOfCharges/ChangeOfChargePipelineTests.cs
ChargeConfirmation and ChargeRejection must implement IMessage enabling correlationId check in integration tests.
=> Reenable pipeline integration tests

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/InputValidationRulesFactoryTests.cs
This PR. will add unittests to to the `InputValidationRulesFactory`. Making sure if any rules are removed from the implementation of either create / update / stop the corresponding test will fail.
=> test: InputValidationRulesFactory

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Factories/ChargeFactoryTests.cs
To ensure that all properties can be mapped going from a `ChargeCommand` to `Charge`.
This PR will introduce a test for the `ChargeFactory`, so if `Charge` is expanded we wont forget map the new property in the `ChargeFactory`.
=> test: ChargeFactory

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/ChargeOperationIdRequiredRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/ChargeOwnerIsRequiredValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/ValidationRuleIdentifier.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/BusinessValidation/ValidationRules/ChangingTariffTaxValueNotAllowedRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/BusinessValidation/ValidationRules/ChangingTariffVatValueNotAllowedRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/BusinessValidation/ValidationRules/CommandSenderMustBeAnExistingMarketParticipantRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/BusinessValidation/ValidationRules/StartDateValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/BusinessReasonCodeMustBeUpdateChargeInformationTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ChargeDescriptionHasMaximumLengthRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ChargeIdLengthValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ChargeIdRequiredValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ChargeNameHasMaximumLengthRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ChargeOperationIdRequiredRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ChargeOwnerIsRequiredValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ChargePriceMaximumDigitsAndDecimalsRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ChargeTypeIsKnownValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ChargeTypeTariffPriceCountRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/DocumentTypeMustBeRequestUpdateChargeInformationTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/FeeMustHaveSinglePriceRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/MaximumPriceRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/OperationTypeValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ProcessTypeIsKnownValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/RecipientIsMandatoryValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ResolutionFeeValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ResolutionSubscriptionValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ResolutionTariffValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/SenderIsMandatoryValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/StartDateTimeRequiredValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/SubscriptionMustHaveSinglePriceRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/VatClassificationValidationRuleTests.cs
This PR. will add tests to ensure that the correct `ValidationRuleIdentifier` is used in the rules containing the input / business validation, so if rules are changed / refactored and another identifier is used by a mistake, a test will now fail.
There were some of the test classes that didn't follow our convention, so i updated their names.
Some of the `ValidationRuleIdentifer` used did not follow our convention of "rulename" _minus the rule part_, so i updated them.
=> test: business/input validation rules

.github/workflows/charge-command-receiver-cd.yml, .github/workflows/charge-command-receiver-ci.yml, .github/workflows/charge-confirmation-sender-cd.yml, .github/workflows/charge-confirmation-sender-ci.yml, .github/workflows/charge-rejection-sender-cd.yml, .github/workflows/charge-rejection-sender-ci.yml, .github/workflows/message-receiver-cd.yml, .github/workflows/message-receiver-ci.yml
Right now we install core tools without using it, in preparation of moving to .NET 5.0
It turns out that it is not needed to install separately as the .NET Core 3.1 runtime which is needed in the pipelines anyway will actually install it.
As a result, the separate unused steps will be removed.
=> Remove core tools from pipelines

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Application/ChangeOfCharges/ChangeOfChargeLocalHostTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Application/ChangeOfCharges/ChangeOfChargePipelineTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/ChargeDbQueries.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/EmbeddedResourceHelper.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/HttpRequestFactory.cs
Description
Replacing CorrelationId we use the more correct ChargeID, Type and Owner to check for the existence of a charge.
=> Check for Charge in database using ChargeID, Type and Owner

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Acknowledgement/ChargeConfirmationSender.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Acknowledgement/ChargeRejectionSender.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Factories/ChargeFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/BusinessReasonCodeMustBeUpdateChargeInformationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/ProcessTypeIsKnownValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChangeOfCharges/Transaction/ChargeOperation.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Charge.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Common/Document.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestFiles/InvalidCreateTariffCommand.json, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestFiles/ValidCreateTariffCommand.json, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/BusinessReasonCodeMustBeUpdateChargeInformationTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ProcessTypeIsKnownValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Builders/ChargeCommandTestBuilder.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Repositories/ChargeRepositoryTests.cs
The purpose of this PR is to move the business reason code field from ChargeOperation to Document; it had been placed on the operation by mistake.
This is a step towards better reusability between Charges and ChargeLinks.
This PR:
* Moves BusinessReasonCode to Document (from Charge and ChargeOperation)
* Updates ChargeConfirmationSender to respect change
* Updates ChargeRejectionSender to respect change
* Updates validation rules to respect change
* Updates unit and integration tests to respect change
* #357
=> Move BusinessReasonCode from Operation to Document

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeLinkReceiver/HealthStatus.cs
The purpose of this PR is to fix the HealthStatus trigger of the ChargeLinkReceiver which is currently failing due to incompatibilie with isolated functions.
=> Make HealthStatus compatible with .NET 5.0 isolated functions

.github/workflows/codecov-ci.yml, codecov.yml
The purpose of this PR is to update now we use codecoverage in the charge domain by renaming the flags to businesslogic and infrastructure and uploading both reports.
=> Update flags used in code coverage

.github/actions/terraform-cd/action.yml, build/infrastructure/main/azfun-charges-message-receiver.tf, build/infrastructure/main/azfun-link-receiver.tf
The purpose of this PR is to update the TLS used in our pipeline to 1.2
Also updates message receiver and link receiver to basic plans to avoid free plan limits.
=> Use TLS 1.2 for tfstate storage account

.github/workflows/codecov-ci.yml, .github/workflows/sonarcloud.yml
Sonarcloud and Codecov now only will run if `./source` is updated our their workflow.
* #0000
=> sonarcloud and codecov workflow only runs on pr if /source or workflow is hit

build/infrastructure/main/azfun-charge-confirmation-sender.tf, build/infrastructure/main/azfun-charge-rejection-sender.tf, build/infrastructure/main/azfun-charges-chargecommandreceiver.tf, build/infrastructure/main/azfun-link-receiver.tf, build/infrastructure/main/azfun-metering-point-created-receiver.tf
This purpose of this PR is to fix the storage account names of functions which was using msgrcvr by mistake.
Also uses our own storage account module for testing before updating shared modules.
* #0000
=> Fix name of storage accounts

build/infrastructure/main/azfun-charge-confirmation-sender.tf, build/infrastructure/main/azfun-charge-rejection-sender.tf, build/infrastructure/main/azfun-charges-chargecommandreceiver.tf, build/infrastructure/main/azfun-charges-message-receiver.tf, build/infrastructure/main/azfun-link-receiver.tf, build/infrastructure/main/azfun-metering-point-created-receiver.tf
Shared storage accounts has now been updated to version 1.2 of TLS, so we go back to using it with this PR.
=> Reintroduce use of shared storage account module

build/infrastructure/main/locals.tf
Reading the values for the user and password directly from the SQL server module to create connection string in local.tf
* #0000
=> chargeDB sql conn string using module to read pw / user

.github/actions/charges-apply-db-migrations/action.yml, .github/actions/terraform-cd/action.yml, .github/workflows/infrastructure-cd.yml, build/infrastructure/main/outputs.tf
Change pipeline to use keyvault to store connection string used by apply db migration action
* #0000
=> Change to store connection string in keyvault

.github/workflows/pr-env-teardown.yml
The purpose of this PR is to fix the PR gateway which is currently failing in its teardown step because the new terraform variables used in the charges domain has not been added to this workflow.
=> Add missing variables to PR teardown

build/infrastructure/env/Test/kv-shared-data.tf, build/infrastructure/env/Test/kv-shared-stub.tf, build/infrastructure/env/Test/sb-external-integration-events.tf, build/infrastructure/env/Test/sb-metering-point-created.tf
The purpose of this PR is to stub the shared resources in the T-environment until the shared resources are up and running correctly.
* #363
=> Stub shared resources in T environment

build/infrastructure/env/Development/kv-shared-data.tf, build/infrastructure/main/azfun-link-event-publisher.tf, build/infrastructure/main/kv-shared-data.tf, build/infrastructure/main/locals.tf, build/infrastructure/main/sb-charges.tf, build/infrastructure/main/sbs-link-command-accepted-event-publisher.tf, build/infrastructure/main/sbt-link-command-accepted.tf
The purpose of this PR is to add enought terraform to be able to deploy a shell for the Charge Link Event Publisher
This PR:
* Adds an isolated Azure Function to Terraform
* Adds some common access rights to our charge service bus namespace
* Adds the integration event sender connection string
* Adds the integration event sender connection string to our development stub
* Adds charge link command accepted topic
* Adds charge link command accepted subcription used by event publisher
* #359
=> Add terraform needed for link event publisher

.github/actions/delete-terraform-state/action.yml, .github/workflows/pr-env-teardown.yml
The purpose of this PR is to make sure we clean up our Terraform state when tearing down environments as part of the PR gateway.
Right now, the state is left in the resource group where we have one extra storage account per PR up until its max of 250 where we will get into a restriction.
=> Fix issue with tfstate surviving teardown

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/ValidationRuleIdentifier.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChangeOfCharges/Transaction/ChargeType.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChangeOfCharges/Transaction/OperationType.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChangeOfCharges/Transaction/Resolution.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChangeOfCharges/Transaction/VatClassification.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/MarketDocument/BusinessReasonCode.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/MarketDocument/DocumentType.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/MarketDocument/IndustryClassification.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/ChargeLinkCommandAccepted.proto, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/ChargeLinkCommandReceived.proto, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestFiles/InvalidCreateTariffCommand.json, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestFiles/ValidCreateTariffCommand.json
This PR will update all enums that are used in the change of charges. All enums now start at 0 and subsequent entries add 1 to the last number eg: 0-1-2-3...
* #440
=> bug - Enums start at zero add one

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Acknowledgements/ChargeConfirmation.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Acknowledgements/ChargeRejection.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Command/CommandBase.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/GreenEnergyHub.Charges.Domain.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/Mapping/ChargeMapper.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/GreenEnergyHub.Charges.Infrastructure.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Messaging/MessageDispatcher.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Messaging/MessageExtractor.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/BusinessValidation/ValidationRules/CommandSenderMustBeAnExistingMarketParticipantRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Core/Json/JsonSerializerTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Messaging/TestableServiceBusChannel.cs
The purpose of this PR is to remove our uses of the JetBrains.Annotation DLL.
We are currently using it for [UsedImplicitly] and often misusing it for [NotNull].
It will be easier to spot if we dont use the DLL at all.
=> refac: Remove use of Jetbrains.Annotation

build/infrastructure/main/azfun-charge-confirmation-sender.tf, build/infrastructure/main/azfun-charge-rejection-sender.tf, build/infrastructure/main/azfun-charges-chargecommandreceiver.tf, build/infrastructure/main/azfun-charges-message-receiver.tf, build/infrastructure/main/azfun-link-command-receiver.tf, build/infrastructure/main/azfun-link-event-publisher.tf, build/infrastructure/main/azfun-link-receiver.tf, build/infrastructure/main/azfun-metering-point-created-receiver.tf, build/infrastructure/main/mag-availability.tf
The purpose of this PR is to add alerts for availability tests to our Azure Functions though Terraform.
This PR:
* Adds an alert for each of our 8 current functions in the charge domain
* Adds the alert group which receives the alerts
* #143
=> Add alerts for availability tests

.github/actions/obtain-terraform-output/action.yml, .github/actions/terraform-cd/action.yml, .github/workflows/infrastructure-cd.yml
The purpose of this PR is to move the Terraform output from the Terraform action to a separate action.
This will make it easier for MightyDucks to later make the Terraform action shared between all domains of GreenEnergyHub.
=> Separate terraform output from shared action

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeLinkCommandReceiver/GreenEnergyHub.Charges.ChargeLinkCommandReceiver.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeLinkCommandReceiver/HealthStatus.cs
The purpose of this PR is to add HealthStatus to ChargeLinkCommandReceiver which is currently missing it.
=> Add HealthStatus to  ChargeLinkCommandReceiver

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Integration/Mappers/ChargeConfirmationInboundMapper.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Integration/Mappers/ChargeRejectionInboundMapper.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/ProtobufDeserializationHelper.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/ServiceBusTestHelper.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Integration/ChargeConfirmationContractEnumTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Integration/ChargeRejectionContractEnumTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Integration/Mappers/ChargeConfirmationInboundMapperTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Integration/Mappers/ChargeRejectionInboundMapperTests.cs
The purpose of this PR is to update the integration tests to use protobuf which is now being used in the domain.
* Updates integration test to use protobuf
* Adds inbound mapper for ChargeConfirmation and ChargeRejection
* #373
=> Fix: Update integration test to use protobuf

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestFiles/InvalidCreateTariffCommand.json, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestFiles/ValidCreateTariffCommand.json
MessageReceiver CD integration test run [failed](https://github.com/Energinet-DataHub/geh-charges/runs/3347657866?check_suite_focus=true) due to `OperationType` still being present in test files.
This PR removes OperationType in the test files.
* #0000
=> fix: Remove `OperationType` from integration test files

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Application/ChangeOfCharges/ChangeOfChargePipelineTests.cs
This PR increases the time out threshold for the integration tests being run in MessageReceiver CD.
The pipeline has failed running the tests several times, and increasing the time out seems to be fixing this.
* #503
=> fix: Increase time out threshold for pipeline integration tests

build/infrastructure/main/azfun-metering-point-created-receiver.tf
The Metering Point did not get a configuration for Charge DB connection string, this PR aims to resolve this issue
* #510
=> fix: add missing connectionstring in Azure function

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/MeteringPoints/ConnectionState.cs
When creating a new metering point we were missing the connection state indicating it was new.
=> ConenctionState.New enum value

.github/workflows/infrastructure-cd.yml, build/infrastructure/main/asp-charges.tf, build/infrastructure/main/azfun-charge-confirmation-sender.tf, build/infrastructure/main/azfun-charge-receiver.tf, build/infrastructure/main/azfun-charge-rejection-sender.tf, build/infrastructure/main/azfun-charges-chargecommandreceiver.tf, build/infrastructure/main/azfun-create-link-command-receiver.tf, build/infrastructure/main/azfun-link-command-receiver.tf, build/infrastructure/main/azfun-link-event-publisher.tf, build/infrastructure/main/azfun-link-receiver.tf, build/infrastructure/main/azfun-metering-point-created-receiver.tf
To save consumption spend in Azure it has been decided to couple all functions on the same app service plan.
This can be differentiated on the preprod and prod environments. - Team MD will come with a solution for these environments soon, that also allows scaling.
=> use the same app service plan for all functions

.editorconfig
There was inconsistency with the team desire to be able to write one-line-if's, and the rule enforcement from .editorconfig.
This PR will update the required bracers style to be required only if the code block now is multiple lines.
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0011#csharp_prefer_braces
=> fix: inconsistent bracers style

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Integration/Mappers/ChargeRejectionOutboundMapperTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Repositories/ChargeRepositoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Repositories/DefaultChargeLinkRepositoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Repositories/MeteringPointRepositoryTests.cs
To ensure we are not just reading from memory in the old context, its been decided to create a new database context for the assert part of database tests
ACs
1. The context used to arrange and act is not the same as the one used to assert that data is valid
* #555
=> refac: use new context for reading database values

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/GreenEnergyHub.Charges.IntegrationTests.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/GreenEnergyHub.Charges.TestCore.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/Squadron/SqlServerOptions.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/GreenEnergyHub.Charges.Tests.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Repositories/ChargeLinkRepositoryTests.cs
The purpose of this PR is work on the StoreAsync_StoresChargeLink test which is currently uncommented due to an unknown issue.
The problem is related to how quickly we use the SQL server within docker through Squadron, which Squadron has partly addressed in their upgrade to 0.12.1.
It is however not enough in our use scenario, so we increade the wait even.
We should consider whether it would be possible to make a better solution where we determine when the SQL server is ready to take on test, but that requires more knowledge of Squadron than we currently have.
This is a quick fix that work around the problem until we get an idea for a solution.
* #334
=> fix: Uncommented chargelink test

.github/workflows/charge-command-receiver-ci.yml, .github/workflows/charge-confirmation-sender-ci.yml, .github/workflows/charge-receiver-ci.yml, .github/workflows/charge-rejection-sender-ci.yml, .github/workflows/codecov-ci.yml, .github/workflows/metering-point-created-receiver-ci.yml, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeCommandReceiver/ChargeCommandEndpoint.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeConfirmationSender/ChargeCommandAcceptedSubscriber.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeLinkCommandReceiver/LinkCommandReceiverEndpoint.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeLinkEventPublisher/ChargeLinkEventPublisherServiceBusTrigger.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeLinkReceiver/ChargeLinkHttpTrigger.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeReceiver/ChargeHttpTrigger.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeRejectionSender/ChargeCommandRejectedSubscriber.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.CreateLinkCommandReceiver/CreateChargeLinksReceiverServiceBusTrigger.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MeteringPointCreatedReceiver/MeteringPointCreatedReceiverEndpoint.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Acknowledgement/ChargeConfirmationSenderTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Acknowledgement/ChargeRejectionSenderTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/FunctionHost/FunctionsShouldBeIncludedInCoverageTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/GreenEnergyHub.Charges.Tests.csproj
Our 94% code coverage is misleading as our functions endpoints are not included. This PR makes sure that they are included by adding a test that targets symbols from all the function hosts.
As an added benefit the test project - and thus also multiple pipelines - has been updated from .NET 3.1 to .NET 5.0.
* #0000
=> Improve misleading code coverage metrics

.github/templates/azure-function-cd-template.yml, .github/templates/azure-function-ci-template.yml, .github/workflows/charge-command-receiver-cd.yml, .github/workflows/charge-confirmation-sender-cd.yml, .github/workflows/charge-receiver-cd.yml, .github/workflows/charge-rejection-sender-cd.yml, .github/workflows/metering-point-created-receiver-cd.yml, .github/workflows/sonarcloud.yml
Fix the CD pipelines that was broken by earlier PR because they appear to actually execute unit tests, which now is a .NET 5 project.
I assume it's a mistake to execute unit tests during CD as they are already executed as part of CI in the PR gate.
* #0000
=> Update all pipelines to .NET 5.0.202

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Application/ChangeOfCharges/ChangeOfChargeLocalHostTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/ProtobufDeserializationHelper.cs
Our localhost integration tests have not been working since the introduction of protobuf in the Charges domain.
This pull request reenables the localhost integration test functionality.
=> Reenable localhost integration tests

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/GreenEnergyHub.Charges.Application.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/GreenEnergyHub.Charges.ApplyDBMigrationsApp.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/GreenEnergyHub.Charges.Core.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/GreenEnergyHub.Charges.Domain.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/GreenEnergyHub.Charges.FunctionHost.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/EntityConfigurations/ChargeLinkEntityConfiguration.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/GreenEnergyHub.Charges.Infrastructure.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/GreenEnergyHub.Charges.IntegrationTests.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/ChargeDbQueries.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/EmbeddedResourceHelper.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/GreenEnergyHub.Charges.TestCore.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/GreenEnergyHub.Charges.Tests.csproj, source/Shared/GreenEnergyHub/source/GreenEnergyHub.Json/GreenEnergyHub.Json.csproj, source/Shared/GreenEnergyHub/source/GreenEnergyHub.TestHelpers/GreenEnergyHub.TestHelpers.csproj, source/iso8601/GreenEnergyHub.Iso8601/GreenEnergyHub.Iso8601.csproj, source/messaging/source/GreenEnergyHub.Messaging.Integration.ServiceCollection/GreenEnergyHub.Messaging.Integration.ServiceCollection.csproj, source/messaging/source/GreenEnergyHub.Messaging.Protobuf.Integration.ServiceCollection/GreenEnergyHub.Messaging.Protobuf.Integration.ServiceCollection.csproj, source/messaging/source/GreenEnergyHub.Messaging.Protobuf/GreenEnergyHub.Messaging.Protobuf.csproj, source/messaging/source/GreenEnergyHub.Messaging/GreenEnergyHub.Messaging.csproj, source/queues/source/GreenEnergyHub.Queues.AzureServiceBus/GreenEnergyHub.Queues.AzureServiceBus.csproj, source/queues/source/GreenEnergyHub.Queues.Kafka/GreenEnergyHub.Queues.Kafka.csproj, source/queues/source/GreenEnergyHub.Queues.ValidationReportDispatcher/GreenEnergyHub.Queues.ValidationReportDispatcher.csproj, source/queues/source/GreenEnergyHub.Queues/GreenEnergyHub.Queues.csproj
The purpose of this PR is to upgrade all projects in Charges to .NET 5,0 and update needed nuget packages to their .NET 5.0 variants.
After this we will be using .NET 5.0 in charges.
This PR:
* Upgrades all remaining projects to target .NET 5.0
* Updates nuget packages to use .NET 5.0 where we were still using 3.1 variants.
* Updates various other nuget packages to latest version
* Fixes EntityFrameWork incompatibility between 3.1 and 5.0 in ChargeLinkEntityConfiguration
* Various small updates to fix types that are now nullable when returned from nuget packages in 5.0 variants.
* Update test project to output protobuf files to 5.0 folder instead of 3.1
In later PR:
* Clean up dependency injection
* Use shared implementation of correlation ID instead of each endpoint having the code …
=> feat: Upgrade projects to .NET 5.0

source/GreenEnergyHub.Charges.Libraries/nuget.config
Removes the nuget.config file which is not actually needed and currently breaks out client CI pipeline.
=> fix: Remove nuget.config

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChargeLinkCommands/ChargeLinkCommandFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Factories/ChargeLinkCommandFactoryTests.cs
When receiving a default charge link factor is always 1
When receiving a ChargeLink the value is defined on
Chargelink period details
This stops the value from always defaulting to 1 for both
cases
* #666
=> fix: issue with default factor value

docs/local-development/run-integration-tests-local.md
As our integrationtest.local.settings.json has changed, the examples mentioned 
in the run-integration-tests-local.md were no longer relevant.
* #691
=> docs: Remove outdated examples in `run-integration-tests-local.md` text

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/Mappers/DefaultChargeLinksCreatedOutboundMapper.cs
Fix nullreference exception in inbound mapper due to missing variable being set in outbound mapper
* #0000
=> fix: set missing variable in outbound mapper

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/Handlers/CreateLinkRequestHandler.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeLinksCommands/DefaultChargeLinksRequestCommandFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeLinksCommands/IDefaultChargeLinksRequestCommandFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/CreateChargeLinkReceiverConfiguration.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Factories/DefaultChargeLinksRequestCommandFactoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/CreateLinkCommandEventHandlerTests.cs
The purpose of this PR is to rename the ChargeLinkCommandFactory to DefaultChargeLinksRequestCommandFactory to signal that it has nothing to do with the normal charge link command flow in BRS-037 and is only used when creating default charge links as part of BRS-004.
* #886
=> refac: Naming of DefaultChargeLink Command Factory

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeIngestionTests.cs
The purpose of this PR is to adjust the time we wait for integration events.
The test are currently blinking alot using the old setting of 10 seconds.
* #0000
=> fix: Adjust test waiting time

source/Energinet.Charges.Libraries/global.json, source/GreenEnergyHub.Charges/global.json
With the present pull request, we introduce the global.json to pin the .Net Core SDK version used.
One global.json is enough to enforce dotnet to a pinned SDK version, but not all IDEs will conform to this version. Therefore a global.json is added for each .Net solution.
* [#305](https://app.zenhub.com/workspaces/team-volt-dev-session-615167844e83ef001107e157/issues/energinet-datahub/geh-timeseries/305)
=> Add global.json for both .Net solutions in Charges domain

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/BusinessValidation/Factories/BusinessValidationRulesFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/BusinessValidation/ValidationRules/ChargeUpdateNotYetSupportedRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/ValidationRuleIdentifier.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Validation/BusinessValidation/Factories/BusinessValidationRulesFactoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Validation/BusinessValidation/ValidationRules/ChargeUpdateNotYetSupportedRuleTests.cs
The purpose of this PR is to add a validation rule which fails requests about a charge that exist in the database.
This will make sure that market participants gets a rejection until we actually implement updates and stops.
This PR:
* Adds business validation rule failing if the charge exist
* Adds the validation rule to the validation rule factory
* Adds and updates tests
* #937
=> feat: Add validation stopping updates to an existing charge

source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/ChargeLinks/ChargeLinksClientTests.cs, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/ChargeLinks/ChargeLinksClient.cs, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/ChargeLinks/ChargesRelativeUris.cs, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md
There was a deserializing issue in the ChargeLinkClient where ChargeLinkDto was not deserialized correctly; no values were set.
This PR fixes the issue by using `new JsonSerializerOptions(JsonSerializerDefaults.Web)`
Edited an existing unit test to cover this issue.
* #792
=> Fix: ChargeLinkClient was not deserializing correctly

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/GreenEnergyHub.Charges.Application.csproj
The purpose of this PR to update the message hub nuget package.
The old version is no longer compatible with the deployed messagehub.
* #0000
=> fix: Update message hub nuget to fix broken integration

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Infrastructure/Bundling/BundleCreator.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Infrastructure/Bundling/BundleReplier.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Infrastructure/Bundling/BundleSender.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Infrastructure/Bundling/IBundleReplier.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Infrastructure/Bundling/UnknownDataAvailableNotificationIdsException.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/MessageHub/BundleCreatorTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/MessageHub/BundleReplierTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/MessageHub/BundleSenderTests.cs
The purpose of this PR is to add support for notifying the message hub of errors instead of just failing and letting the message hub wait in suspense.
Hopefully this will help on two of our current issues:
* That we sometimes get errors in our CI which is not actual there
* That we get wiser about why the error in the CI and errors in the environments occur (by logging the information)
This PR:
* Adds new exception thrown when we find no available data on the IDs requested by the message hub
* Catches exceptions in the bundle sender so that it can reply with errors to the message hub (which then does not have to wait for time out)
* Logs information about errors so we can get wiser on the current issues
* Replies to the message hub with two different kind of errors depending on situation …
=> feat: Add errorflow support when speaking with message hub

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Fixtures/ChargesFunctionAppFixture.cs
Sets the missing environment variable in domain tests
* #879
=> fix: Set missing test environment variable

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Helpers/UpgradeFactory.cs
The default 30 seconds often timed out, therefor this
increases the timeout to 2 minutes to allow for slow
responding services.
* #989
=> refac: increase database migration timeout

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/Handlers/ChargeLinksDataAvailableNotifiedPublisher.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/Handlers/CreateDefaultChargeLinksReplyHandler.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/ChargeLinkDataAvailableReplyHandlerTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/CreateDefaultChargeLinksReplyHandlerTests.cs
The responsibility of whether to reply (BRS-004) is the responsibility of the replier and should not be entangled with the Message Hub code.
* #0000
=> Move BRS-004 reply responsibility to replier

build/infrastructure/main/locals.tf
There is still a timeout issue in the action `Applying database migrations` done in the Charges CD pipeline. 
This was not solved by #991 alone. 
This PR should fix this issue.
Error shown:
````
System.Data.SqlClient.SqlException (0x80131904): Connection Timeout Expired.  The timeout period elapsed during the post-login phase.  The connection could have timed out while waiting for server to complete the login process and respond; Or it could have timed out while attempting to create multiple active connections.  The duration spent while attempting to connect to this server was...
`````
* #0000
=> Solving the timeout issue occuring in the action `applying database migrations`

.github/dependabot.yml
With his PR Dependabot is set up to check for dependencies for both .NET solutions in the Charges domain
* #868
=> Re-enable dependabot for both .NET solutions

.github/workflows/ci.yml
With this PR, we apply the newly created workflow for publishing Web APIs `dotnet-create-webapi-artifact.yml` found in the v. 2.7.0 release of the .github repo. At the same time, the rest of the workflows in the ci.yml are bumped to v. 2.7.0.
This PR fixes the issue where the Charges Web API always returns 404 not found.
This fix was tested previously by applying the solution to this PR and manually deploying it to U-001 after which the Charges Web API responded as expected.
* #827
=> Use latest v.2.7.0 release of the .github repo to be able to properly deploy Charges Web API

source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/ChargeLinks/ChargeLinksClientTests.cs, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/ChargeLinks/ChargeLinksClient.cs, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md
The Charges Web API (`ChargeLinksController`) passes the `ChargeType` enum as a string instead of the int value. 
This PR adapts the `ChargeLinkClient` to handle this by using `JsonStringEnumConverter`.
* #827
=> Update `ChargeLinksClient` to handle enum passed as string from Charges Web API (Use `JsonStringEnumConverter`)

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/local.settings.sample.json
Fixed subscription name, so we are able to run function-host locally against an environment. 
* #0000
=> Fix incorrect subscription in `local.settings.sample.json`

build/infrastructure/main/func-functionhost.tf, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Model/202201281340 Increase OriginalOperationId length.sql
This PR fixes some misconfiguration revealed by app-insights for the subscriptions needed for 
* ChargeLinksEventPublisherEndpoint
* ChargeLinkDataAvailableNotifierEndpoint
* ChargeLinkConfirmationDataAvailableNotifierEndpoint
It is planned to [extend our deep health check](https://github.com/Energinet-DataHub/geh-charges/pull/1054), so it also covers these subscriptions going forward.
Also, we've found that the OriginalOperationId length used in two DataAvailable must be increase to hold GUID values.
* #0000
=> Fix - misconfiguration related to downstream Charge Links Endpoints

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Data.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/IData.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/Charge.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/ChargeLink.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/ChargePoint.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/DefaultChargeLink.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/GridArea.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/GridAreaLink.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/MarketParticipant.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/MeteringPoint.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/QueryDbContext.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/scaffold-query-stack.ps1, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.WebApi/Controllers/OData.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.WebApi/GreenEnergyHub.Charges.WebApi.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.WebApi/Startup.cs
Enables testers to inspect the data in the system without the need for e.g. database tools and hard to obtain credentials.
The OData API is discoverable through the Swagger API.
To explore more in-depth try out queries like:
- List all market participants: `<base-url>/odata/marketparticipants`
- Show charges owned by each market participant: `<base-url>/odata/marketparticipants?$expand=charges($select=senderprovidedchargeid)`
- List 3 metering points: `<base-url>/odata/meteringpoints?$top=3`
Learn more about what can be done using an OData API [here](https://docs.microsoft.com/en-us/odata/concepts/queryoptions-overview).
Please note that I had to add data annotations in the scaffolding as the key annotation is required by the OData framework. I checked but there is, unfortunately, no …
=> Enable query access to the data in the charges domain

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeLinksCommands/Validation/BusinessValidation/Factories/ChargeLinksCommandBusinessValidationRulesFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeLinksCommands/Validation/BusinessValidation/ValidationRules/ChargeLinksUpdateNotYetSupportedRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Persistence/Repositories/ChargeLinksRepository.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Builders/ChargeLinkDtoBuilder.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Core/Enumeration/EnumValueNameComparisonStrategyFactoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeLinksCommands/Validation/BusinessValidation/ValidationRules/ChargeLinksUpdateNotYetSupportedRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/MessageHub/BundleTypeMapperTests.cs
ChargeLinks with an open-ended end date is persisted with a fixed maximum date. The temporary _ChargeLinks update and stop is not yet supported_-rule did not take this into account, which is now fixed.
A few minor unrelated improvements without functional impact are included.
* #1087
=> ChargeLinks update and stop requests doesn't return reject bug is fixed

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/ServiceCollectionExtensions.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/SharedConfiguration.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Program.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Authentication/JwtTokenWrapperMiddleware.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/GreenEnergyHub.Charges.Infrastructure.Core.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/ActorProvider.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeIngestionTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeLinkIngestionTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/SynchronizeFromActorRegisterTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/SystemTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Fixtures/FunctionApp/ChargesFunctionAppFixture.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/AuthenticatedHttpRequestGenerator.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/HttpRequestGenerator.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure.Core/MessagingExtensions/Factories/ServiceBusMessageFactoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure.Core/MessagingExtensions/Registration/RegistrationTests.cs
Re-enable authentication requirement for all relevant function host HTTP endpoints.
Authentication was disabled in an earlier PR today as it caused a dead-lock in the actor test environment (invocation of synchronization of actors into the domain required an actor in the domain - kinda catch 22).
This PR also adds missing tests asserting that the ingestion endpoints (the HTTP endpoints that the market participants send market documents to) actually require authentication.
I don't consider this the final authentication solution. The `JwtTokenWrapperMiddleware` is a workaround that we'll most likely want to refactor. But for now, I believe we prefer a quick reenabling of basic security requiring a valid bearer token in order to send market documents to the charges domain.
* #1105
=> Re-enable authentication for selected HTTP endpoints

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/clients-ci.yml, .github/workflows/clients-registration-ci.yml, .github/workflows/sonarcloud-check.yml, source/Energinet.Charges.Libraries/global.json, source/GreenEnergyHub.Charges/global.json, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/MessagingExtensions/MessageExtractor.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/MessagingExtensions/Serialization/JsonMessageDeserializer.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/MessagingExtensions/ValidatingMessageExtractor.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Infrastructure/Bundling/BundleSender.cs
Energinet .github workflow dependencies are updated to the latest version (4.0.0), except for dotnet-create-function-artifact.yml which is updated to 3.0.2, the latest version without a bug, that is present in 3.0.3 and 4.0.0.
In addition, the CA2007 reliability rule is handled in three cases where the rule wasn't earlier forced.
=> Update Energinet .github workflow version

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Function/HttpResponseBuilder.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeIngestionTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeLinkIngestionTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/ApiManagementTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/MyDomainTests.cs
This PR fixes a bug which made `ChargeIngestion` and `ChargeLinkIngestion` return `StatusCode 200 OK` instead of `StatusCode 202 Accepted` for schema valid requests.
The problem was that `await httpResponse.WriteAsJsonAsync(response).ConfigureAwait(false);` changed our response.statuscode from 202 to 200.
* #1127
=> Fix: Return `StatusCode 202 Accepted` instead of 200 OK - for charges and charge links requests

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/InputValidation/Factories/ChargeCommandInputValidationRulesFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeLinksCommands/Validation/InputValidation/Factories/ChargeLinksCommandInputValidationRulesFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/Validation/IInputValidationRulesFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/Validation/InputValidator.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Cim/ValidationErrors/CimValidationErrorTextToken.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeLinksReceiptData/ChargeLinksCimValidationErrorTextFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeReceiptData/ChargeCimValidationErrorTextFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/InputValidation/ChargeCommandInputValidationRulesFactoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeLinksCommands/Validation/InputValidation/ChargeLinksCommandInputValidationRulesFactoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeLinkReceiptData/ChargeLinksCimValidationErrorTextFactoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeReceiptData/ChargeCimValidationErrorTextFactoryTests.cs
ChargeOwner and ChargeType are now set in error texts for charge link rejection messages.
* #1087 
* #938
=> Fix missing ChargeOwner and ChargeType in error message

source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/ChargeLinks/ServiceCollectionExtensions/ServiceCollectionExtensions.cs, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/documents/release-notes/release-notes.md, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.RegistrationTests/ChargeLinks/ServiceCollectionExtensionsTests.cs, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/ChargeLinks/ChargeLinksClientFactoryTests.cs, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/ChargeLinks/ChargeLinksClientTests.cs, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/Energinet.DataHub.Charges.Clients.Tests.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/ChargeLinks/ChargeLinksClientFactory.cs, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/ChargeLinks/IChargeLinksClientFactory.cs, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/GreenEnergyHub.Charges.TestCore.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/HttpContextAccessorMock.cs
Endpoint deep security is enabled on the Charges WebAPI and the BFF must now forward JWT token from DataHub GUI to the Charges Web API. With this PR the `ChargeLinksClient` will extract the token from any request using `IHttpContextAccessor` and forward the token in the request to the Charges Web API.
* #1088
=> ChargeLinksClient will forward token

source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/ChargeLinks/ChargeLinksClientTests.cs, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/ChargeLinks/ChargeLinksClient.cs, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/ChargeLinks/IChargeLinksClient.cs, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md
DataHub BFF is not yet ready to use `ChargeLinkV2Dto`, so we roll back to `ChargeLinkV1Dto` in this v2.0.2 of the Charges.Clients NuGet Package pull request
* #1088
=> #1088 charges clients should not yet use charge link v2 dto

build/infrastructure/main/sb-charges.tf
Charges CD showed this terraform issue while attempting deployment:
This PR adds the missing permissions to the "manage" auth rule.
* #0000
=> Fix - add listen and send permissions to sb_charges.tf as required by terraform

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/Authorization/AuthorizationConfiguration.cs
The frontend-open-id-url used for acquiring a token for frontend authentication is now environment-specific in the B2C. This pull request adapts Charges WebAPI integration tests to use the environment-specific frontend open id url.
=> Use new environment-specific frontend-open-id-url

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/InputValidation/ValidationRules/ChargeTypeTariffPriceCountRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/InputValidation/ValidationRules/ChargeTypeTariffPriceCountRuleTests.cs
This PR removes some shortcomings in the way VR.507-1 `ChargeTypeTariffPriceCountRule ` is currently implemented:
* It allows master data only requests through (requests with no prices)
* It doesn't throw when resolution = P1M (monthly)
But be aware that it still rejects price series longer than a day of values.
Nevertheless, I do believe we need to reconsider this validation rule; 
* is it fit for a CIM context in its current state? 
* Should it be applied on all types of charges?
* Should it only assert that the number of Points match the time interval of the price series?
* Should we perhaps add a new validation rule for restricting price series shorter than 1 day of points?
I'll note this on the story as well for further discussion. For now, this PR will bring the validation rule to a …
=> Fix: Validation Rule VR.507-1 `ChargeTypeTariffPriceCountRule` to NOT block master data only requests and not throw when `Resolution = P1M`

docs/business-processes/validations.md
VR630 has already been removed from code base, but it still appears in the validations.md.
This PR just removes it from that .md as well.
* #1136
=> Remove `VR630` from validations.md

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Persistence/EntityConfigurations/ChargeEntityConfiguration.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/Repositories/ChargeRepositoryTests.cs
Sets precision and scale for Charge Price to 14.6
to match what is set at database level
When persisting only the first 2 decimals are saved
Fixes #1216
* #1216
=> fix: set precision and scale for charge price

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/DateTime/InstantExtensions.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestHelpers/EmbeddedResourceHelper.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Infrastructure/Cim/Bundles/Charges/ChargeCimSerializer.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/TestFiles/ExpectedOutputChargeCimSerializerMasterDataAndPrices.blob, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/TestFiles/ExpectedOutputChargeCimSerializerPricesWithoutMasterData.blob
Issue: When notifying market participants about charge prices the date time format used in `<cim:start>` and `<cim:end>` was incorrect.
This PR corrects the format used, making it pass schema validation.
**Incorrect**
````
<cim:timeInterval>
<cim:start>2022-05-01T22:00:00Z</cim:start>
<cim:end>2022-05-02T22:00:00Z</cim:end>
</cim:timeInterval>
````
**Correct:**
````
<cim:timeInterval>
<cim:start>2022-05-01T22:00Z</cim:start>
<cim:end>2022-05-02T22:00Z</cim:end>
</cim:timeInterval>
````
https://github.com/Energinet-DataHub/green-energy-hub/issues/286
=> Fix: Use correct ISO8601 format `yyyy-MM-ddTHH:mmZ` in `<cim:start>` and `<cim:end>` which represents `timeInterval` of a price series

docs/business-processes/validations.md, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Cim/ValidationErrors/CimValidationErrorTextTemplateMessages.cs
This PR; 
Changes the error text provided for VR.505-2 so it now writes "Month" instead of "Day". 
In Validations.md - VR.505-2 is updated and VR.507-2 is removed (no longer applicable)
* #1245
=> Correcting an error text and updating validations.md

build/infrastructure/main/app-webapi.tf
Updating the Web API runtime version in Azure to .NET 6 (defaults to .NET 5).
=> Web API .NET 6

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/GreenEnergyHub.Charges.ApplyDBMigrationsApp.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Model/202204191415 Ensure unique charges by removing duplicates and adding constraint.sql, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/Repositories/ChargeRepositoryTests.cs
This PR is the second - and last - part of the fix for #1276.
With this PR any duplicate charges that may have been inserted into the Charges database are removed, including their ChargePeriods, Points and Charge Links that may have been created. 
This PR also adds a unique constraint on the Charge table, so attempts to insert a charge that already exists (based on `SenderProvidedChargeId`, `Type` and `OwnerId`) will result in an exception.
* #1276
=> Fix: Remove duplicate charge entries in the database and add unique constraint on `SenderProvidedChargeId`, `Type` and `OwnerId`

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/ReplySender/ServiceBusReplySenderProvider.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/ReplySender/CreateDefaultChargeLinkReplier/CreateDefaultChargeLinkReplierTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/ReplySender/ServiceBusReplySenderProviderTests.cs
Bug #1262 was caused by multiple concurrent calls to the `ServiceBusReplySenderProvider.GetInstance()` method which caused the method to try and add the same key to the `_senders` dictionary. The dictionary is changed to `ConcurrentDictionary` and a stress test is added.
Note for reviewers: Chages in `CreateDefaultChargeLinkReplierTests` are non-functional line-changes.
* #1262
=> 'Senders'-dictionary handles concurrent requests

codecov.yml
Re-introduce codecov.yml with the purpose to omit the Charges domain tests-projects from the CodeCov report.
=> Omit test projects from CodeCov-report

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Handlers/ChargeCommandReceivedEventHandler.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/Repositories/AvailableDataRepositoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Builders/MessageHub/AvailableChargeDataBuilder.cs
This PR fixes the bug where charge operations for the same charge was not sent out (notifications) in the same chronological order as they were received in the inbound request.
Also, this PR adds a test to the AvailableDataRepositoryTests to ensure that GetAsync upholds the expected ordering of data, which will be the basis for the notifaction message generation.
* #1143
=> Fix: List operations in notifications chronologically

.github/workflows/ci.yml
As this [issue](https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/132) in GitHub action markdown link check has been fixed, Team Mighty Ducks has requested us to degrade to v. 6.2.0 again.
* #0000
=> Degrade ci-base to version 6.2.0 as requested by Mighty Ducks

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeData/AvailableChargeDataFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeLinksData/AvailableChargeLinksDataFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/BusinessProcessTests.cs
When peeking a `NotifyPriceList` aka Charge notification or a `NotifyBillingMasterData` aka Charge Link notificaiton , the HTTP header `MessageType` did not contain the correct value. This PR fixes this issue
MessageType now contains **NotifyPriceList** for charge notifiations
And **NotifyBillingMasterData** for charge link notifications
Also, the system test for a Charge creation now asserts correct MessageType value on Charge notification.
* Incident 169
=> Fix: Incorrect HTTP Header `MessageType` value applied to notifications - charge and charge links

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Handlers/ChargeCommandReceivedEventHandler.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Handlers/ChargeHandler.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Handlers/ChargeCommandReceivedEventHandlerTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Handlers/ChargeHandlerTests.cs
BusinessReasonCode is used in ChargeHandler
which comes before Document validation, therefor
an invalid code will throw an exception.
The document validation is now moved ahead of
ChargeHandler so it will also validate the Charge
Prices flow.
* #1305 
* #1339
=> refac: move document validation

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/MarketParticipants/DocumentType.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Cim/MarketDocument/DocumentTypeMapper.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Infrastructure/Cim/Bundles/ChargeLinkReceipt/ChargeLinksReceiptCimSerializer.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeLinksReceiptData/AvailableChargeLinksReceiptDataFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeLinksReceiptData/AvailableChargeLinksRejectionDataFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/Shared/AvailableDataFactoryHelper.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Builders/Command/ChargeLinksCommandBuilder.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure.Core/Cim/MarketDocument/DocumentTypeMapperTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/BundleSpecification/ChargeLinks/ChargeLinksRejectionBundleSpecificationTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Infrastructure/Cim/Bundles/ChargeLinksReceipt/ChargeLinkReceiptCimSerializerTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeLinkReceiptData/AvailableChargeLinkReceiptDataFactoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeLinkReceiptData/AvailableChargeLinkRejectionDataFactoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeReceiptData/AvailableChargeConfirmationDataFactoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeReceiptData/AvailableChargeRejectionDataFactoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/Shared/AvailableDataFactoryHelperTests.cs
At the moment, when a market partipant peeks a charge link confirmation or rejection message an incorrect value is set in the `MessageType` HTTP header.
With this PR, the MessageType for Charge Link Confirmation will be set to `ConfirmRequestChangeBillingMasterData` whereas Rejection will be `RejectRequestChangeBillingMasterData`
* #1340
=> Fix: Use correct `MessageType` HTTP header for Charge Links `confirmation` and `rejection` messages

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/CimDeserialization/MarketDocument/DocumentConverter.cs
Fix: Avoid responding with HTTP status 500, when `sender_MarketParticipant.mRID` and `receiver_MarketParticipant.mRID` are empty.
With this PR, you will get the following behavior:
* an **empty sender** will result in sync HTTP status 400 "Sender mismatch".
* and an **empty receiver** will result in a async validation error (RecipientIsMandatoryTypeValidationRule)
Deployed draft PR in U-001 and tested: 
Happy flow still OK 😉 
Empty sender got the following sync rejection:
````
<Error>
<Code>B2B-008</Code>
<Message>The sender organization provided in the request body does not match the organization in the bearer token.</Message>
</Error>
````
Empty receiver had the following async rejection:
````
<cim:Reason>
<cim:code>D02</cim:code>
<cim:text>Recipient is missing for message …
```
=> Fix: Avoid responding with HTTP status 500, when `sender_MarketParticipant.mRID` and `receiver_MarketParticipant.mRID` are empty

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/Handlers/CreateLinkRequestHandler.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/MeteringPoints/Handlers/MeteringPointPersister.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Function/FunctionInvocationLoggingMiddleware.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeLinksReceiptData/AvailableChargeLinksRejectionDataFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeReceiptData/AvailableChargeRejectionDataFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeReceiptData/ChargeCimValidationErrorTextFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/MeteringPoints/Handlers/MeteringPointPersisterTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure.Core/Function/FunctionInvocationLoggingMiddlewareTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeLinkReceiptData/AvailableChargeLinkRejectionDataFactoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeReceiptData/AvailableChargeRejectionDataFactoryTests.cs
Messages provided to `Microsoft.Extensions.Logging` must be a static template string, for the logging to function optimally, as informed by [CA2254](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2254).
All usages of `Microsoft.Extensions.Logging` are now invoked with a static template string and optionally a dynamic message as `params[]` argument using the solution proposed [here](https://github.com/dotnet/roslyn-analyzers/issues/5626#issuecomment-1033240500)
=> refactor: Provide message template string for logging framework

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Cim/ValidationErrors/CimValidationErrorTextTemplateMessages.cs
This PR improves a few error texts by using `business reason code` instead of the 'ebix' wording `energy business process`.
* #1305
=> Fix: Error texts to use the wording "Business reason code" instead of "Energy business process"

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/InputValidation/Factories/ChargeOperationInputValidationRulesFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/InputValidation/ChargeOperationInputValidationRulesFactoryTests.cs
This bug fix will make sure we differentiate and provide the correct rules for charge information operation and charge price operation, respectively.
* #1292
=> fix: 1292 Provide correct rules for price operation

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/HealthCheckConfiguration.cs
This is the second of multiple pull requests covering [issue 1409](https://app.zenhub.com/workspaces/team-volt-60a61059028fd7000e49956e/issues/energinet-datahub/geh-charges/1409).
These tasks were solved in an earlier pull request:
With this we solve the following task:
Upcoming tasks:
* #1409
=> feat: Add ChargePriceCommandReceivedTopic to health checks

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/MarketParticipants/Handlers/MarketParticipantDomainEventMapper.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/MarketParticipants/Handlers/MarketParticipantPersister.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/MarketParticipantsUpdatedEvents/MarketParticipantUpdatedEvent.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/MarketParticipants/Handlers/MarketParticipantDomainEventMapperTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/MarketParticipants/Handlers/MarketParticipantPersisterTests.cs
If an actor integrationevent from the market participant domain  is received with more than 1 role associated an invalidoperation exception is thrown and no operations is done, the same will happen if a market participant is already persisted with the marketparticipant id that is included in the actor event, but with a different role than the one included in the actor event
* #1208
=> fix: throws exception if persisting a marketparticipant with an exisiting id but different role

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/MessageHub/AvailableDataNotificationFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/MessageHub/AvailableDataNotificationFactoryTests.cs
A mismatch in the use of ActorId for DataAvailable notifications to MessageHub entails a rollback to use GLN while we figure out how to properly use ActorID
* #1345
=> Use LegacyActorIdDto to provide GLN for dataavailable notifications

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/CimDeserialization/ChargeBundle/ChargeCommandConverter.cs
Charge owner and charge type now just parses on the default value of string.empty, instead
of throwing an exception while trying to read the empty value. At the same time the
existing .CanReadValue uses have been streamlined to look the same for better readability.
* #1326
=> fix: avoid throwing exceptions when XML values are empty

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Cim/ValidationErrors/CimValidationErrorTextTemplateMessages.cs
Upon request by our SME, this PR changes the error text used, when Charge Type is missing in the Charge Information Request.
* #0000
=> Fix: Changed error text for ChargeTypeIsKnownValidation

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Persistence/Repositories/MarketParticipantRepository.cs
Feat: Always select active Metering Point Administrator and System Operator from Market Participant table. 
(This has been an issue while switching to Market Participant integration events)
* #1345
=> Feat: Always select active Metering Point Administrator and System Operator

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/MarketParticipant/MarketParticipantPersisterEndpoint.cs
Adds logger to MarketParticipantPersisterEndpoint that logs the integration event type received.
* #1345
=> Debug: Add logger to MarketParticipantPersisterEndpoint to get the type of integration event received

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeLinkIngestionTests.cs
For now, ChargeLinkCommandConverter splits all CIM MktActivityRecord into separate ChargeLinkCommands
so we do not always receive a rejection due to the parallel handling of commands. This behavior caused a test to be unreliable as the system sometimes returned two confirmed messages and other times one confirmed and one rejected message. Therefore the check for a rejected message is no longer mandatory, but if a rejected message is present then it must be rejected due to a violation of the `ChargeLinksUpdateNotYetSupportedRule`.
=> Conditionally check for reject-message

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/GreenEnergyHub.Charges.Application.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/MarketParticipants/Handlers/MarketParticipantDomainEventMapper.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/MarketParticipants/Handlers/MarketParticipantRoleMapper.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Helpers/ConnectionStringFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/SharedDtos/MarketParticipantRole.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/GreenEnergyHub.Charges.FunctionHost.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/GreenEnergyHub.Charges.Infrastructure.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/EndpointTests/MarketParticipantPersisterEndpointTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/MarketParticipants/Handlers/MarketParticipantDomainEventMapperTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/MarketParticipants/Handlers/MarketParticipantEventHandlerTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/MarketParticipants/Handlers/MarketParticipantRoleMapperTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/GreenEnergyHub.Charges.Tests.csproj
Grid area is now a data type nested to market role in the MarketParticipant domain. This pull request updates the Energinet.DataHub.MarketParticipant.Integration.Model NuGet package in Charges domain to the version containing the new data model and reflects the changes in mappers within Charges domain.
* #1208
* #1345
=> feat: Grid areas are nested to market roles

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/clients-ci.yml, .github/workflows/clients-registration-ci.yml
As a temporary solution to overcome an issue running integration tests using Azure resources, we have decided to disable integration tests in the CI pipeline, so for now, we use `dotnet-solution-ci.yml` branch `temporarily_disable_integration_test` to temporarily disable running integration tests using Azure resources.
And last but not least, this is temporary! and must be followed up by a new pull request with a solution to the issue of running integration tests using Azure resources.
=> fix: Temporarily disable integration tests in CI

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/GreenEnergyHub.Charges.Application.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/GreenEnergyHub.Charges.FunctionHost.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/GreenEnergyHub.Charges.Infrastructure.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/EndpointTests/GridAreaLinkPersisterEndPointTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/EndpointTests/MarketParticipantPersisterEndpointTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/MarketParticipants/Handlers/MarketParticipantDomainEventMapperTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/MarketParticipants/Handlers/MarketParticipantEventHandlerTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/GreenEnergyHub.Charges.Tests.csproj
Team Titans has taken the first steps towards publishing micro-events from the Market Participant domain.
With this pull request, the charges domain takes the latest _Energinet.DataHub.MarketParticipant.Integration.Model_ Nuget package to use.
[Market Participant issue #632](https://app.zenhub.com/workspaces/titans-60d029726fc7570010362aa7/issues/energinet-datahub/geh-post-office/632)
=> Use latest MarketParticipant integration model

docs/business-processes/asynchronous-validations.md, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Handlers/IChargePriceCommandBundleHandler.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/Factories/ChargeOperationInputValidationRulesFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/ChargeIdLengthValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/ChargeNameHasMaximumLengthRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/ChargeOperationIdLengthValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/ChargeOperationIdRequiredRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/ChargeOwnerIsRequiredValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/ChargePriceMaximumDigitsAndDecimalsRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/ChargeTypeIsKnownValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/ChargeTypeTariffPriceCountRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/MaximumPriceRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/NumberOfPointsMatchTimeIntervalAndResolutionRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/ResolutionFeeValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/ResolutionSubscriptionValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/ResolutionTariffValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/ResolutionValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/StartDateTimeRequiredValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/TransparentInvoicingIsNotAllowedForFeeValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/VatClassificationValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeLinksCommands/ChargeLinksCommandBundle.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/Validation/ValidationRuleIdentifier.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Cim/ValidationErrors/CimValidationErrorTextTemplateMessages.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Function/IHttpResponseBuilder.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/Shared/CimValidationErrorCodeFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/ApiManagementTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/InputValidation/ChargeOperationInputValidationRulesFactoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/InputValidation/ValidationRules/ChargeOperationIdLengthValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure.Core/MessagingExtensions/Serialization/JsonMessageDeserializerTests.cs
A new validation rule is introduced: Charge requests where `OperationID` (`cim:MktActivityRecord` > `cim:mRID`) is longer than 36 characters are rejected asynchronously.
* #1492
=> feat: Reject Charges requests where OperationID is longer than 36 characters

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/GreenEnergyHub.Charges.ApplyDBMigrationsApp.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Model/202201281340 Increase OriginalOperationId length.sql, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Model/202207151427 Increase OriginalOperationId length.sql, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeLinksReceiptData/AvailableChargeLinksReceiptDataFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeLinksReceiptData/AvailableChargeLinksRejectionDataFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeReceiptData/AvailableChargeReceiptDataFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeReceiptData/AvailableChargeRejectionDataFactory.cs
The new ChargeOperationIdLengthValidationRule rejects requests containing operationId longer than 36 characters. To be able to tell the sender of the message that the operationId was too long, we increase the allowed characters in data available tables to 100 and substring the value if it is longer than that.
* #1492
=> Allow up to 100 characters for rejections

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/NumberOfPointsMatchTimeIntervalAndResolutionRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/InputValidation/ValidationRules/NumberOfPointsMatchTimeIntervalAndResolutionRuleTests.cs
TotalDays will be a decimal, slightly less than or slightly more than an integer, which will then fail when comparing the number of actual periods with the expected periods.
* #1494
=> fix: will handle DST correctly on P1D/P1M resolution

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/TaxIndicatorMustBeFalseForFeeValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/TaxIndicatorMustBeFalseForSubscriptionValidationRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/InputValidation/ValidationRules/TaxIndicatorMustBeFalseForFeeValidationRuleTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/InputValidation/ValidationRules/TaxIndicatorMustBeFalseForSubscriptionValidationRuleTests.cs
When submitting a charge information request (D18) where taxIndicator is omitted from the request, like seen below, then it triggers the following validation rules, depending on the charge type; fee or subscription: 
* `TaxIndicatorMustBeFalseForSubscriptionValidationRule`
* `TaxIndicatorMustBeFalseForFeeValidationRule`
````
````
This results in two errors in the provided rejection message:
````
<cim:Reason>
<cim:code>E0H</cim:code>
<cim:text>Tax indicator must be set when calling with BusinessReasonCode D18 for charge type Subscription with charge ID SubId013 owned by 9656626091925.</cim:text>
</cim:Reason>
<cim:Reason>
<cim:code>D14</cim:code>
<cim:text>Tax indicator cannot be true for charge ID SubId013 owned by 9656626091925 as it is of charge type Subscription.</cim:text> …
```
=> Fix: TaxIndicatorMustBeFalse validation rules should not trigger when TaxIndicator is unknown

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/clients-ci.yml, .github/workflows/clients-registration-ci.yml
Speed up CI execution time by using default .NET Core SDK version pre-installed on hosted Github Runner
Reference: https://github.com/Energinet-DataHub/the-outlaws/issues/360
=> Remove DOTNET_VERSION

source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.IntegrationTests/Energinet.DataHub.Charges.Clients.IntegrationTests.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/documents/release-notes/release-notes.md, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.RegistrationTests/Energinet.DataHub.Charges.Clients.RegistrationTests.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/Energinet.DataHub.Charges.Clients.Tests.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/GreenEnergyHub.Charges.Core.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/GreenEnergyHub.Charges.Infrastructure.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/GreenEnergyHub.Charges.TestCore.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/GreenEnergyHub.Charges.Tests.csproj
This PR updates several NuGet packages to latest version, as pointed out by dependabot August 1st.
Updates packages for Charges and Charges.Libraries and bumps the version of the Charges.library package (3.0.6)
* #0000
=> Chores - versions bumps - August 2022

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/Validation/ValidationRuleIdentifier.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Cim/ValidationErrors/CimValidationErrorTextTemplateMessages.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/Shared/CimValidationErrorCodeFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/Shared/CimValidationErrorCodeFactoryTests.cs
This PR removes some 'leftovers' related to two former validation rules: 
* FeeMustHaveSinglePrice
* SubscriptionMustHaveSinglePrice
They've both been replaced by a new validation rule: 
`ValidationRuleIdentifier.NumberOfPointsMatchTimeIntervalAndResolution`
* #0000
=> Remove: Fee&SubscriptionMustHaveSinglePrice validation rule 'leftovers'

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/CimDeserialization/ChargeBundle/ChargeCommandBundleConverter.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/GreenEnergyHub.Charges.IntegrationTest.Core.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestFiles/Charges/ChargeDocument.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestFiles/Charges/PriceSeries/BundledSubscriptionPriceSeriesSecondOperationChargeOwnerMismatch.xml, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeIngestionTests.cs
While testing #1419, a deviation was detected when the submitted request was a bundled charge price request (D08) with 3 operations, whereof the 2nd operation had mismatching owner value. Here two rejection messages were received with similar content for 2nd and 3rd operation. 
Expected was 1x rejection message for 2nd operation, and a confirmation message(s) for 1st and 3rd operation.
This PR fixes a grouping bug in the `ChargeCommandConverter` that caused the same bundled charge price request to be processed more than once; why the two rejection messages were received during testing.
This PR adds a domain test verifying that a bundled charge price request (D08) with 3x operations, where the 2nd fails on ChargeOwnerMismatch, receives one rejection and two confirmation messages, covering …
=> Fix: Grouping bug in `ChargeCommandConverter` caused bundled price requests to be processed more than once

source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.IntegrationTests/Energinet.DataHub.Charges.Clients.IntegrationTests.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/documents/release-notes/release-notes.md, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.RegistrationTests/Energinet.DataHub.Charges.Clients.RegistrationTests.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/Energinet.DataHub.Charges.Clients.Tests.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md, source/GreenEnergyHub.Charges/global.json, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/GreenEnergyHub.Charges.Core.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/GreenEnergyHub.Charges.Infrastructure.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/GreenEnergyHub.Charges.IntegrationTest.Core.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/GreenEnergyHub.Charges.IntegrationTests.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/GreenEnergyHub.Charges.SystemTests.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/GreenEnergyHub.Charges.TestCore.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/GreenEnergyHub.Charges.Tests.csproj, source/Shared/GreenEnergyHub/source/GreenEnergyHub.TestHelpers/GreenEnergyHub.TestHelpers.csproj
All NuGet dependencies in the _Charges.Libraries_ solution are updated to the latest version:
In addition a the above packages were also updated in GreenEnergyHub.Charges solution and we now use .NET Core SDK 6.0.400
* #1579
=> Update dependencies in Charges.Libraries solution

docs/business-processes/asynchronous-validations.md
With this PR, the async validation rules md file now clearly shows which rules apply to D18 and D08.
* #0000
=> Docs: Separating D08 and D18 in `async validation rules md` for a better overview

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Charges/Charge.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Charges/ChargeTests.cs
This PR fixes the problem where a charge, that was created and stopped the same date, wouldn't allow a cancel stop operation.
Now...
* It allows a Charge to be persisted with a charge period where start and end date are equal.
* Upon cancelling the stop, it removes the charge period with matching start and end date.
* #1289
=> Fix: Allow "CancelStop" on a charge that was created and subsequently stopped the same date

source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.IntegrationTests/Energinet.DataHub.Charges.Clients.IntegrationTests.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/documents/release-notes/release-notes.md, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.RegistrationTests/Energinet.DataHub.Charges.Clients.RegistrationTests.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/Energinet.DataHub.Charges.Clients.Tests.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/GreenEnergyHub.Charges.Application.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/GreenEnergyHub.Charges.ApplyDBMigrationsApp.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/GreenEnergyHub.Charges.Domain.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/GreenEnergyHub.Charges.FunctionHost.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/GreenEnergyHub.Charges.Infrastructure.Core.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/GreenEnergyHub.Charges.Infrastructure.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/GreenEnergyHub.Charges.IntegrationTest.Core.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/GreenEnergyHub.Charges.IntegrationTests.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/GreenEnergyHub.Charges.MessageHub.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/GreenEnergyHub.Charges.SystemTests.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/GreenEnergyHub.Charges.Tests.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.WebApi/GreenEnergyHub.Charges.WebApi.csproj, source/Shared/GreenEnergyHub/source/GreenEnergyHub.TestHelpers/GreenEnergyHub.TestHelpers.csproj
This PR bumps the following packages:
**Charges:**
Azure.Messaging.ServiceBus to 7.10.0
dbup-sqlserver to 4.6.0
Energinet.DataHub.Core.Messaging to 2.1.1
Energinet.DataHub.Core.Messaging.Protobuf to 2.1.1
Energinet.DataHub.Core.Messaging.Protobuf.Integration.ServiceCollection to 2.1.1
Energinet.DataHub.Core.Schemas to 2.1.1
Energinet.DataHub.MarketParticipant.Integration.Model to 2.5.1
Energinet.DataHub.MessageHub.Client to 3.1.0
Energinet.DataHub.MessageHub.IntegrationTesting to 3.1.0
GreenEnergyHub.Charges.FunctionHost to 2.2.1
Grpc.Tools to 2.48.1
Microsoft.ApplicationInsights.AspNetCore to 2.21.0
Microsoft.AspNetCore.Mvc.Testing to 6.0.8
Microsoft.AspNetCore.OData to 8.0.11
Microsoft.NET.Test.Sdk to 17.3.1
Swashbuckle.AspNetCore to 6.4.0
**Charges.Libraries:**
Grpc.Tools to 2.48.1 …
=> Chores - september 2022 - Bump nuget packages used by Charges

source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/documents/release-notes/release-notes.md, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/ChargeLinks/ChargesRelativeUris.cs, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md
This PR is the first of a few towards displaying both ChargeOwner (GLN) and ChargeOwnerName (Market Participant name, aka. company name)
First issue that needs to be fixed is; change the routing in the ChargeLinksClient, so it targets the `v1/GetChargeLinks` in Charges.WebApi instead of `v2`
v1 = the contract `ChargeLinkV1Dto` which has `ChargeOwner` and `ChargeOwnerName`
v2 = the contract `ChargeLinkV2Dto` which contains `ChargeOwnerId` instead of the two above mentioned.
This will fix the response the BFF receives, where `ChargeOwner` is null.
Additional steps are needed to fill `ChargeOwnerName` , so it will continue to be a hardcoded value after merging this PR.
Also, a PR is needed in the BFF (repo: greenforce-frontend) updating to the latest Clients and Clients.Registration packages …
=> Fix: ChargeLinksClient calls routed to v1/GetChargeLinks (instead of v2)

source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/documents/release-notes/release-notes.md, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/ChargeLinks/ChargesRelativeUris.cs, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/V1/ChargeLinksControllerTests.cs
The `ChargeLinksClient` in the package `Energinet.DataHub.Charges.Clients` was using an incomplete charges web api endpoint URL, which resulted in the BFF getting a `HTTP 405 Method not allowed` back. 
This PR fixes this.
* #1123
=> Fix: `ChargeLinksClient` used an incomplete URL when request charge links for a metering point

build/infrastructure/main/func-functionhost.tf, build/infrastructure/main/sbt-charges-domain-events.tf, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Acknowledgement/ChargePricesUpdatedPublisher.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Acknowledgement/IChargePricesUpdatedPublisher.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Factories/ChargePricesUpdatedEventFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Handlers/ChargePriceIntegrationEventsPublisher.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Handlers/IChargePriceIntegrationEventsPublisher.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Charges/ChargePriceIntegrationEventsPublisherEndpoint.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Common/EnvironmentSettingNames.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/ChargePriceCommandReceiverConfiguration.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/ChargePriceIntegrationEventsPublisherEndpointConfiguration.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/HealthCheckConfiguration.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Program.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/local.settings.sample.json, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/Fixtures/FunctionApp/ChargesFunctionAppFixture.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/Fixtures/FunctionApp/ChargesServiceBusResourceNames.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeIngestionTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Factories/ChargePricesUpdatedFactoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Handlers/ChargeIntegrationEventsPublisherTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Handlers/ChargePriceIntegrationEventsPublisherTests.cs
The charge  price flow will send integration events to other domains when confirmed/accepted chargeprices (D08) has been ingested, handled and persisted
* #1562
=> feat: split chargeprice integration event from old flow into new chargeprice flow

build/infrastructure/main/sbt-charges-domain-events.tf
module "sbts_charges_charge_command_received" used label `ChargeCommandReceivedEvent`, while it was recently changed in the code base to `ChargeInformationCommandReceivedEvent`
* #0000
=> Fix broken system test: rename label used by subscription `ChargeInformationCommandReceivedEvent`

build/infrastructure/main/sbt-charges-domain-events.tf
`ChargeCommandAcceptedEvent` and `ChargeCommandRejectedEvent` were renamed in an earlier PR to 
`ChargeInformationCommandAcceptedEvent` and `ChargeInformationCommandRejectedEvent`.
The subscriptions listening for those events were by mistake not aligned, breaking the Charge Information flow (caught by our system test).
This PR aligns the subscription labels to the new event names.
* #1527
=> Fix: Charge Information flow broken due to renamed ChargeInformation events

source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.IntegrationTests/Energinet.DataHub.Charges.Clients.IntegrationTests.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/documents/release-notes/release-notes.md, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.RegistrationTests/Energinet.DataHub.Charges.Clients.RegistrationTests.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/Energinet.DataHub.Charges.Clients.Tests.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj, source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/GreenEnergyHub.Charges.Application.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/GreenEnergyHub.Charges.Core.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/GreenEnergyHub.Charges.Domain.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/GreenEnergyHub.Charges.FunctionHost.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/GreenEnergyHub.Charges.Infrastructure.Core.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/GreenEnergyHub.Charges.Infrastructure.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/GreenEnergyHub.Charges.IntegrationTest.Core.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/GreenEnergyHub.Charges.IntegrationTests.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/GreenEnergyHub.Charges.MessageHub.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/GreenEnergyHub.Charges.SystemTests.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/GreenEnergyHub.Charges.TestCore.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/GreenEnergyHub.Charges.Tests.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.WebApi/GreenEnergyHub.Charges.WebApi.csproj, source/Shared/GreenEnergyHub/source/GreenEnergyHub.TestHelpers/GreenEnergyHub.TestHelpers.csproj, source/iso8601/GreenEnergyHub.Iso8601/GreenEnergyHub.Iso8601.csproj
Upgrading nuget packages for charges and charge client library, reported from depandabot.
Bumps Energinet.DataHub.MessageHub.Client from 3.1.0 to 3.3.0.
Bumps Energinet.DataHub.Core.TestCommon from 3.4.0 to 3.5.0.
Bumps Energinet.DataHub.Core.App.WebApp from 7.0.0 to 7.1.0.
Bumps Microsoft.Extensions.Diagnostics.HealthChecks from 6.0.8 to 6.0.9.
Bumps Energinet.DataHub.Core.SchemaValidation from 1.0.13 to 2.1.1.
Bumps SimpleInjector from 5.4.0 to 5.4.1.
Bumps Microsoft.NET.Test.Sdk from 17.3.1 to 17.3.2.
Bumps Google.Protobuf from 3.21.5 to 3.21.7.
Bumps NodaTime from 3.1.2 to 3.1.3.
Bumps Grpc.Tools from 2.48.1 to 2.49.1.
* #0000
=> Depandabot upgrades october

.github/workflows/cd.yml, .github/workflows/ci.yml
Added a dotnet_latest release, that always will be up to date with the latest released package
BE AWARE that we will do another iteration splitting infrastructure away from the dotnet package, so this is only to introduce a non breaking rollout
=> use new create-latest-release  workflow

.github/CODEOWNERS
Update CodeOwners to consist of only current Volt team members (and one former member) as well as Mighty Ducks. Others are removed.
* #0000
=> Repo: Removed people from CodeOwners in Charges

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Infrastructure/Cim/Bundles/Charges/ChargePriceCimJsonSerializer.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Infrastructure/Cim/Bundles/Charges/ChargePriceCimJsonSerializerTests.cs
With this PR, a JSON charge price notification (D08) will now list price series in ascending order based on the position value.
Also, a shuffling of price test data was added to an existing test, to verify that this ordering actually works.
* #0000
=> Fix: Price series ordered ascending in JSON notifications (based on position value)

source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.IntegrationTests/Energinet.DataHub.Charges.Clients.IntegrationTests.csproj, source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj, source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/documents/release-notes/release-notes.md, source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.RegistrationTests/Energinet.DataHub.Charges.Clients.RegistrationTests.csproj, source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/Energinet.DataHub.Charges.Clients.Tests.csproj, source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj, source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/GreenEnergyHub.Charges.Application.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/GreenEnergyHub.Charges.Core.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/GreenEnergyHub.Charges.Domain.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/GreenEnergyHub.Charges.Infrastructure.Core.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/GreenEnergyHub.Charges.IntegrationTest.Core.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/GreenEnergyHub.Charges.IntegrationTests.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/GreenEnergyHub.Charges.MessageHub.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/GreenEnergyHub.Charges.SystemTests.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/GreenEnergyHub.Charges.TestCore.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/GreenEnergyHub.Charges.Tests.csproj, source/Shared/GreenEnergyHub/source/GreenEnergyHub.TestHelpers/GreenEnergyHub.TestHelpers.csproj, source/iso8601/GreenEnergyHub.Iso8601/GreenEnergyHub.Iso8601.csproj
Dependencies with updates identified by dependabot are updated.
Charges:
Charge.Libraries:
=> chore: Update dependencies identified by dependabot - mid October

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/GreenEnergyHub.Charges.ApplyDBMigrationsApp.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Seed/202210201120 Add ChargePeriod to Charges without any.sql
Early on, it was possible to create a new charge and subsequently stop it on the same date it was created. This resulted in the charge not having a charge period in the persistence layer. This is no longer the case, but the data remains.
This PR adds a SQL seed script, which finds all charges without any charge, and adds a charge period. 
This data fix is needed in order for Charges Web API to deliver charge data to frontend in B-002. 
* #0000
=> Data fix: add a `ChargePeriod` to charges without any

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Charges/Charge.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Charges/ChargeTests.cs
This PR removes this code section in `Charge.Update()`:
Code cannot be reached due to validation rule VR.917, which guards any requests where `termination date` does not equal `effective date`. Without this rule it would have been possible to reach Charge.Update with an newChargePeriod.EndDateTime that was not equal `EndDefault`;
Right now, for an operation deemed `charge update`, the new charge period created will be set to `EndDefault` as `chargeInformationOperationDto.EndDateTime` is null: 
* #1231
=> Fix: Remove irrelevant `newChargePeriod.EndDateTime` check in `Charge.Update()`: true cannot be reached

codecov.yml
This helps avoid useless hints in IntegrationTest.Core and GreenEnergyHub.Charges.TestCore about lines not being covered by unittests when doing PR reviews.
Not sure if its better to rename IntegrationTest.Core to IntegrationTest**s**.Core which would make the current rules catch it.
* #0000
=> test: update ignored projects from code coverage

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/DateTime/ZonedDateTimeService.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/ChargeInformation/ChargeInformationCommandReceivedEventHandlerTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/QueryServices/ChargePricesQueryServiceTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/TestHelpers/ZonedDateTimeServiceHelper.cs
This PR fixes the integration test related to  `ChargePricesQueryServiceTests` that fails when running in CI pipeline.
It does that by extending the `ZonedDateTimeService` which willl be providing dates for test data.
Two other integration tests are failing, related to the POC managed resources integration tests, those are skipped as they will be handled in a separate PR.
* #0000
=> Test: Fix (and skip) integration tests that fails in CI pipeline

.github/workflows/ci.yml, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/MessageHub/OutboxMessageProcessorEndpoint.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/EndpointTests/Charges/OutboxMessageProcessorEndpointTests.cs
To trace both before and after outbox processing a log is needed to join operationid on each side.
This PR only adds the logging, the joining will happen in a separate PR.
* #1770
=> feat: add log correlation id in outbox processor

source/Contracts/ChargeMessage/ChargeMessageType.cs, source/Contracts/ChargeMessage/ChargeMessageV1Dto.cs, source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj, source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/documents/release-notes/release-notes.md, source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj, source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Handlers/ChargeInformation/ChargeInformationMessagePersister.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Handlers/ChargePrice/ChargePriceMessagePersister.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Charges/ChargeMessage.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/EndpointTests/Charges/ChargePriceMessagePersisterEndpointTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/QueryServices/ChargeMessagesQueryServiceTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/V1/ChargeMessagesControllerTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/GreenEnergyHub.Charges.QueryApi.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/ChargeMessage.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/QueryServices/ChargeMessageQueryService.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/Builders/Command/ChargeMessageBuilder.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/Builders/Query/ChargeMessagesSearchCriteriaV1DtoBuilder.cs, wordlist.txt
To differentiate between `ChargeInformation` messages and `ChargePrice` messages we need to replace `DocumentType` with `BusinessReasonCode` as `MessageType`. 
* #1689
=> fix: ChargeMessageType reflects BusinessReasonCode

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargePriceCommands/Validation/InputValidation/ValidationRules/NumberOfPointsMatchTimeIntervalAndResolutionRule.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargePriceCommands/Validation/InputValidation/ValidationRules/NumberOfPointsMatchTimeIntervalAndResolutionRuleTests.cs
unknown resolution in validation do not throw an exception for rule "NumberOfPointsMatchTimeIntervalAndResolutionRule"
* #1652
=> fix: unknown resolution in validation do not throw an exception

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/GreenEnergyHub.Charges.ApplyDBMigrationsApp.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Helpers/CustomScriptProvider.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Helpers/ResultReporter.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Helpers/SqlAppAuthenticationProvider.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Helpers/UpgradeFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Program.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/ApplyDBMigrationsApp/Helpers/ResultReporterTests.cs
We are replacing DbUp with a fork called DbUp.Reboot to cater for SQL IAM authentication instead of SQL Auth w/username + password in connectionstrings
Reference: https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/660
=> SQL IAM authentication using DbUp.Reboot

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/QueryServices/ChargeMessagesQueryServiceTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/QueryServices/ChargeMessageQueryService.cs
The date range as provided by UI now includes the whole range from midnight of the `fromDate` to the millisecond before midnight on the day after `endDate`, so no need to add a day in the backend search.
=> fix: Use searchcriteria daterange as provided by UI

source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.IntegrationTests/Energinet.DataHub.Charges.Clients.IntegrationTests.csproj, source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj, source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/documents/release-notes/release-notes.md, source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.RegistrationTests/Energinet.DataHub.Charges.Clients.RegistrationTests.csproj, source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/Energinet.DataHub.Charges.Clients.Tests.csproj, source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj, source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/GreenEnergyHub.Charges.Application.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/GreenEnergyHub.Charges.Core.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/GreenEnergyHub.Charges.FunctionHost.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/GreenEnergyHub.Charges.Infrastructure.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/GreenEnergyHub.Charges.IntegrationTest.Core.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/GreenEnergyHub.Charges.IntegrationTests.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/GreenEnergyHub.Charges.SystemTests.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/GreenEnergyHub.Charges.TestCore.csproj, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/GreenEnergyHub.Charges.Tests.csproj, source/Shared/GreenEnergyHub/source/GreenEnergyHub.TestHelpers/GreenEnergyHub.TestHelpers.csproj
Update dependencies identified by dependabot in December 2022, except:
* packages related to .net 7
* Energinet packages with breaking changes (handled by #1895)
=> chore: Update dependencies, December 2022

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Factories/ChargeHistoryFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Factories/IChargeHistoryFactory.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Handlers/ChargeInformation/ChargeHistoryPersister.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/ChargeHistoryPersisterEndpointConfiguration.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/HealthCheckConfiguration.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/Builders/Command/ChargeInformationOperationsAcceptedEventBuilder.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Factories/ChargeCreatedEventFactoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Factories/ChargeHistoryFactoryTests.cs, source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Handlers/ChargeInformation/ChargeHistoryPersisterTests.cs
When the `ChargeInformationOperationsAcceptedEvent` contains a brand new charge, the `EndDateTime` is `null`.
This was not anticipated and the `ChargeHistoryPersisterEndpoint` threw an `ArgumentNullException`.
This PR now handles this scenario, by setting `EndDefault` when `null` through a new `ChargeHistoryFactory.cs`.
Also, the service bus subscription failing has been fixed. Kudos @HenrikSommer for your great :eyes:
Also, I spotted an incorrect document type used in a builder, and changed it (unrelated to the bug).
* #1846
=> Fix: Charge History Persister to cope with `EndDateTime` being `null`
