.github/templates/azure-function-cd-template.yml
.github/workflows/business-validator-cd.yml
.github/workflows/input-validator-cd.yml
.github/workflows/local-message-service-bus-trigger-cd.yml
.github/workflows/message-receiver-cd.yml

remove documentation update dispatching until later

---

NOTICE.md

Added email md style error check in .md file
* #0000

Fixed email address in .md file

---

NOTICE.md
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChangeOfCharges/Repositories/ChargeStorageStatus.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChangeOfCharges/Repositories/IChargeRepository.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChangeOfCharges/Transaction/ChangeOfChargesTransaction.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChangeOfCharges/Transaction/ChargeTypePeriod.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChangeOfCharges/Transaction/MktActivityRecordStatus.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/ChargesDatabaseContext.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/IChargesDatabaseContext.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/Model/Charge.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/Model/ChargePrice.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/Model/ChargeType.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/Model/MarketParticipant.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/Model/ResolutionType.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/Model/VATPayerType.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/GreenEnergyHub.Charges.Infrastructure.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Mapping/ChangeOfChargesMapper.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Repositories/ChargeRepository.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Builders/ChangeOfChargesTransactionBuilder.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/GreenEnergyHub.Charges.Tests.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Repositories/ChargeRepositoryTests.cs

Migrated IChargeRepository.cs and its implementation and unit tests from green-energy-hub-archived.
It has been decided to neither refactor nor redesign the code but basically just migrate it to geh-charges. Thus this PR provides a handle for persisting change of charge transactions. This will be done in an upcoming PR.
* https://dev.azure.com/energinet/Datahub/_workitems/edit/118414

Migrate ChargeRepository from green-energy-hub-archived

---

NOTICE.md

Update NOTICE.md with new confluent.kafka version

---

build/infrastructure/localhost.tfvars.sample

Add helpful comments to help others avoid already encountered pitfalls.
* #0000

Add comments to localhost.tfvars.sample

---

.github/workflows/infrastructure-cd.yml
build/infrastructure/appi.tf
build/infrastructure/azfun-charges-message-receiver.tf
build/infrastructure/azfun-charges-validator.tf
build/infrastructure/kv-charges.tf
build/infrastructure/sb-charges.tf
build/infrastructure/sqlsrv-charges.tf

Pipelines automatically used latest Terraform version. The latest apparently broke something. So version is from now on fixed and requires action to be updated.
Also, we need a fix from updated Terraform modules thus bumping from version 1.0 to 1.2.
* #0000

Fix broken infrastructure pipeline

---

CONTRIBUTING.md
NOTICE.md

The CONTRIBUTION.md linked to Getting-started in GEH, not the GEH CONTRIBUTION file. This was corrected.
Aligned the wording for contacting us in the NOTICE.md so it aligns with the time series repo.
* #0000

FixContributionLinkAndAligningNoticeFileText

---

source/iso8601/GreenEnergyHub.Iso8601.Tests/GreenEnergyHub.Iso8601.Tests.csproj
source/iso8601/GreenEnergyHub.Iso8601.Tests/Iso8601DurationsTests.cs
source/iso8601/GreenEnergyHub.Iso8601/GreenEnergyHub.Iso8601.csproj
source/iso8601/GreenEnergyHub.Iso8601/IIso8601ConversionConfiguration.cs
source/iso8601/GreenEnergyHub.Iso8601/IIso8601Durations.cs
source/iso8601/GreenEnergyHub.Iso8601/Iso8601ConversionConfiguration.cs
source/iso8601/GreenEnergyHub.Iso8601/Iso8601Durations.cs

Copy ISO 8601 library from green-energy-hub-archived as-is.
* #0000

Add ISO 8601 lib from geh-archived

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChangeOfCharges/Transaction/ChargeTypePeriod.cs

A minor code refactoring broke JSON deserialization of ChargeCommand.cs DTO.
This PR fixes the problem. I hope/expect us to soon have integration tests covering this problem.
* #0000

Fix broken ChargeCommand DTO

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/InputValidationRulesFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/DocumentTypeMustBeRequestUpdateChargeInformation.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/ValidationRuleIdentifier.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/DocumentTypeMustBeRequestUpdateChargeInformationTest.cs

This PR will add the VR404 input validation rule and add it to the mandatory input tests.
* #193

input validation rule VR404

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/InputValidationRulesFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/BusinessReasonCodeMustBeUpdateChargeInformation.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/ValidationRuleIdentifier.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/BusinessReasonCodeMustBeUpdateChargeInformationTest.cs

This PR will add the VR424 input validation rule and add it to the mandatory input tests.
* #193

input validation rule VR424

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeCommandNullChecker.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/InputValidationRulesFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/ChargeIdRequiredValidationRule.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/ValidationRuleIdentifier.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeCommandNullCheckerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ChargeIdRequiredValidationRuleTest.cs

This PR will add the VR440 input validation rule and add it to the mandatory input tests.
* #193

input validation rule VR440

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/GreenEnergyHub.Charges.Tests.csproj

Removed NSubstitute from tests project as we have previously decided to replace it with Moq
* #0000

Removed NSubstitute from tests project as we have replaced it with Moq

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/InputValidationRulesFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/StartDateTimeRequiredValidationRule.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/ValidationRuleIdentifier.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/StartDateTimeRequiredValidationRuleTests.cs

This PR will add the VR531 input validation rule and add it to the mandatory input tests.
* #193

Implemented VR531

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/InputValidationRulesFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/ChargeTypeIsKnownValidationRule.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/ValidationRuleIdentifier.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChangeOfCharges/Transaction/ChargeType.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ChargeTypeIsKnownValidationRuleTest.cs

This PR will add the VR449 input validation rule and add it to the mandatory input tests.
* #193

Implemented VR449

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeCommandNullChecker.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/InputValidationRulesFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/ChargeOwnerIsRequiredValidationRule.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/ValidationRuleIdentifier.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeCommandNullCheckerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ChargeOwnerIsRequiredValidationRuleTests.cs

This PR will add the VR532 input validation rule and add it to the mandatory input tests
* #193

implemented VR532

---

.github/workflows/charge-command-receiver-cd.yml
.github/workflows/charge-confirmation-sender-cd.yml
.github/workflows/charge-rejection-sender-cd.yml
.github/workflows/message-receiver-cd.yml

Integration test without depending on all envs

---

.github/workflows/charge-command-receiver-cd.yml
.github/workflows/charge-confirmation-sender-cd.yml
.github/workflows/charge-rejection-sender-cd.yml
.github/workflows/message-receiver-cd.yml

Fix integration test in pipelines

---

.github/workflows/charge-command-receiver-cd.yml
.github/workflows/charge-confirmation-sender-cd.yml
.github/workflows/charge-rejection-sender-cd.yml
.github/workflows/message-receiver-cd.yml

Fix syntax error in CD pipelines

---

.github/workflows/charge-command-receiver-cd.yml
.github/workflows/charge-confirmation-sender-cd.yml
.github/workflows/charge-rejection-sender-cd.yml
.github/workflows/message-receiver-cd.yml

In checkout action remove path prop

---

.github/actions/integration-test/action.yml
.github/workflows/charge-confirmation-sender-cd.yml
.github/workflows/charge-rejection-sender-cd.yml
.github/workflows/message-receiver-cd.yml
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Application/ChangeOfCharges/ChangeOfChargePipelineTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/local.settings.json.sample

Fix integration test env variables and keyvault

---

.github/actions/integration-test/action.yml

Fix keyvault secret names

---

.github/actions/integration-test/action.yml

Don't fetch non-existing keyvault secret

---

.github/workflows/charge-command-receiver-cd.yml
.github/workflows/charge-confirmation-sender-cd.yml
.github/workflows/charge-rejection-sender-cd.yml
.github/workflows/message-receiver-cd.yml

Fix integration test project name

---

.github/workflows/charge-command-receiver-cd.yml
.github/workflows/charge-confirmation-sender-cd.yml

Try to fix execution of integration test dll

---

.github/workflows/integration-test-ci.yml

Bug fix for integration test CI

Bug fix integration test CI

---

.github/workflows/charge-command-receiver-cd.yml
.github/workflows/charge-confirmation-sender-cd.yml
.github/workflows/charge-rejection-sender-cd.yml
.github/workflows/message-receiver-cd.yml
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Application/ChangeOfCharges/ChangeOfChargeLocalHostTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Application/ChangeOfCharges/ChangeOfChargePipelineTests.cs

This PR disables integration-test for all CD workflows but ChargeCommandReceiver, for which there is a change it will run.

Change of charges integrationtest14

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Application/ChangeOfCharges/ChangeOfChargePipelineTests.cs

Test-output from integration tests for debugging purposes.

Pipeline integration test test-output

---

.github/actions/integration-test/action.yml

Verbose logging to CI console for integration test debugging

Verbose logging to CI console

---

.github/actions/integration-test/action.yml
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Application/ChangeOfCharges/ChangeOfChargePipelineTests.cs

Timeout added to integration test

Change of charges integrationtest17

---

source/GreenEnergyHub.Charges/GreenEnergyHub.Charges.sln.DotSettings
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Application/ChangeOfCharges/ChangeOfChargeLocalHostTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Application/ChangeOfCharges/ChangeOfChargePipelineTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/ChargeDbQueries.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/DbContextRegistrator.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/EmbeddedResourceHelper.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/FunctionHostConfigurationHelper.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/HttpRequestFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/ServiceBusTestHelper.cs

Most renamings were discussed at a team developers session today.
* #0000

Improve naming of test helpers

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChangeOfCharges/Transaction/ChargeType.cs

Fix breaking change to ChargeType enum

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Application/ChangeOfCharges/ChangeOfChargePipelineTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/ServiceBusTestHelper.cs

Assert OriginalTransactionReferenceMRid equals document.Id

Change of charges integrationtest22

---

.github/workflows/message-receiver-cd.yml

Fix github actions workflow syntax

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/Model/ChargePrice.cs

ChargePrice's Retired date should be nullable. 
* #202

chargeprices retired date should be nullable

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ResolutionTariffValidationRuleTests.cs

Expanded the ResolutionTariffValidationRuleTests tariff test to ensure unknown integer values are handled correctly
* #0000

Expanded ResolutionTariffValidationRuleTests

---

README.md

This PR updates the README.md in the Charges domain with current PI goals. 
None
* #0000

Update Charges repo with current program increment goals

---

.github/workflows/sonarcloud.yml

The purpose of this PR is to update the way our SonarCloud pipeline works, so that it supports both ..NET 3.1 and .NET 5.0

Update SonarCloud pipeline to support both .NET 3.1 and .NET 5.0

---

.github/workflows/link-receiver-cd.yml
.github/workflows/link-receiver-ci.yml
build/infrastructure/azfun-link-receiver.tf
source/GreenEnergyHub.Charges/GreenEnergyHub.Charges.sln
source/GreenEnergyHub.Charges/deploy-from-localhost.cmd
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeLinkReceiver/ChargeLinkHttpTrigger.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeLinkReceiver/GreenEnergyHub.Charges.ChargeLinkReceiver.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeLinkReceiver/HealthStatus.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeLinkReceiver/Program.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeLinkReceiver/Properties/serviceDependencies.json
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeLinkReceiver/Properties/serviceDependencies.local.json
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeLinkReceiver/host.json
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeLinkReceiver/local.settings.sample.json

The purpose of this PR is to add the shell of the Azure Function will be receiving charge links.
The function itself is lightweight for now, just returning HTTP 200 to anything sent at it.
The project and pipelines utilize .NET 5.0 in preparation for charges moving to .NET 5.0 entirely later.
This PR adds:
* ChargeLinkReceiver project with the function
* Terraform for deploying the function
* Update to our deployment from local script to support the new function
* A change to the deployment from local script to use correct variable name
* CI pipeline for the ChargeLinkReceiver
* CD pipeline for the ChargeLinkReceiver
* #362

Add Shell for Function receiving Charge Links

---

build/infrastructure/README.md

With this PR we add further instructions to infrastructure readme regarding terraform and Azure.

Update readme with instructions to set Azure subscription

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChangeOfCharges/Repositories/IMarketParticipantRepository.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeCommandNullChecker.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/BusinessValidation/Factories/BusinessCreateValidationRulesFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/BusinessValidation/Factories/BusinessUpdateValidationRulesFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/BusinessValidation/ValidationRules/CommandSenderMustBeAnExistingMarketParticipantRule.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/BusinessReasonCodeMustBeUpdateChargeInformationRule.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/DocumentTypeMustBeRequestUpdateChargeInformationRule.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Validation/InputValidation/ValidationRules/ProcessTypeIsKnownValidationRule.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Acknowledgements/ChargeConfirmation.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Acknowledgements/ChargeRejection.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChangeOfCharges/Transaction/ChargeCommand.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChangeOfCharges/Transaction/ChargeOperation.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Charge.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/MarketDocument/BusinessReasonCode.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/MarketDocument/Document.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/MarketDocument/DocumentType.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/MarketDocument/IndustryClassification.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/MarketDocument/MarketParticipant.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/MarketDocument/MarketParticipantRole.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Mapping/IMarketParticipantMapper.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Mapping/MarketParticipantMapper.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Mapping/MarketParticipantRoleMapper.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Repositories/MarketParticipantRepository.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Repositories/QueryLogic/MarketParticipantQueryLogic.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/BusinessValidation/ValidationRules/CommandSenderMustBeAnExistingMarketParticipantRuleTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/BusinessReasonCodeMustBeUpdateChargeInformationTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/DocumentTypeMustBeRequestUpdateChargeInformationTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Validation/InputValidation/ValidationRules/ProcessTypeIsKnownValidationRuleTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Builders/ChargeCommandTestBuilder.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Repositories/ChargeRepositoryTests.cs

The purpose of this PR is to change the name space of our Document class resides from Common to MarketDocument to make it easier to find and have a more descriptive name.
This PR only contains this namespace change as some housekeeping by removing unused namespaces in the affected files.
* #357

Change namespace of document from Common to MarketDocument

---

.github/workflows/infrastructure-cd.yml

A typo was introduced, this PR will rename mastrix to matrix.

Infrastructure-CD renamed mastrix to matrix

---

build/infrastructure/main/azfun-charges-message-receiver.tf
build/infrastructure/modules/storage-account/main.tf
build/infrastructure/modules/storage-account/outputs.tf
build/infrastructure/modules/storage-account/variables.tf

The purpose of this PR is to test setting TLS to 1.2 in a module before making a PR on the shared modules that could potential stop all domains from working.

Use own storage account on one function as a test

---

.github/workflows/sonarcloud.yml

The purpose of this PR is to fix SonarCloud which can occasionally fail because it is missing the GITHUB_TOKEN.

Fix blinking SonarCloud

---

.github/actions/charges-apply-db-migrations/action.yml
.github/actions/terraform-cd/action.yml
.github/workflows/infrastructure-cd.yml
build/infrastructure/main/outputs.tf

This PR will fix the issues with the Infrastructure-CD pipeline not being able to read the needed values for the ApplyDbMigrations because the Terraform part was moved into its own action.
* #0000

Terraform action outputs the charges sql server connection string

---

.github/actions/charges-apply-db-migrations/action.yml

Removed quotes from the sql server connection string parameter in the ApplyDBMigrations action.
* #0000

removed qutes from the con string parameter in ApplyDBMigrations action

---

.github/actions/terraform-cd/action.yml
.github/workflows/infrastructure-cd.yml

This PR will move the ApplyDBMigrations step into the Terraform action as a temporary fix.
* #0000

ApplyDbMigrations step moved into terraform action

---

.github/actions/terraform-cd/action.yml

Typo fix in the path to the ApplyDBMigrationsApp executable.
* #0000

Terraform actions "step" ApplyDbMigrations path update

---

.github/actions/terraform-cd/action.yml
.github/workflows/infrastructure-cd.yml
build/infrastructure/main/locals.tf
build/infrastructure/main/sqlsrv-charges.tf

This PR will store user/pw in data to be later retrieved by local.tf to create a connectionstring to the charges SQL db.
* #0000

SQL user/pw in data to be used by local.tf

---

build/infrastructure/main/sqlsrv-charges.tf

This PR will remove the data containing the user and pw for the SQL-server. 
* #0000

removed data for pw and user from sqlsrv-charges

---

build/infrastructure/main/locals.tf

Typo fix in locals.tf with correct module name.
* #0000

locals.tf update to charge db con string

---

.github/workflows/infrastructure-cd.yml

Previous PR had a typo in the keyvault-name variable name.
* #0000

Fix wrong variable name in infrastructure pipeline

---

.github/actions/terraform-cd/action.yml
.github/workflows/infrastructure-cd.yml

Fix wrong variable name in db migrations

---

.github/actions/terraform-cd/action.yml

Fixes the path being checked by the existance check before copying files
* #0000

Fix path for directory to check for existance

---

build/infrastructure/main/sb-charges.tf

To make testing of #366 easier a subscription is needed
* #0000

build: Added charge link accepted subscription

---

build/infrastructure/main/sb-charges.tf

We also need a listener to make the subscription useful
* #0000

build: add sb topic auth rule listener

---

.github/workflows/metring-point-created-receiver-cd.yml

Fixed spelling error in github actions CD for MeteringPoint
* #0000

build: fix spelling error in MP CD

---

.github/actions/delete-terraform-state/action.yml

Add auto-confirmation to cleanup of terraform state

---

.github/workflows/link-event-publisher-cd.yml
.github/workflows/link-event-publisher-ci.yml
source/GreenEnergyHub.Charges/deploy-from-localhost.cmd

The purpose of this PR is to add CI and CD pipelines for the new Charge Link Event Publisher.
This PR:
* Adds the CI pipeline for the Event Publisher
* Adds the CD pipeline for the Event Publisher
* Adds the Event Publisher to our script for deploying to development sandbox
* #359

build: CI/CD pipelines for link event publisher

---

build/infrastructure/main/azfun-link-command-receiver.tf
build/infrastructure/main/sb-charges.tf

Fixed wrongly named sender topic and removed unused subscription 
* #0000

build: fix wrong topic and unused sub

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ChargeLinkCommandReceiver/Program.cs

fix: dependency injection error

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/GreenEnergyHub.Charges.Application.csproj
source/Shared/GreenEnergyHub/source/GreenEnergyHub.TestHelpers/GreenEnergyHub.TestHelpers.csproj

In #510 an error was introduced with multiple versions of Microsoft.Extensions.Logging.Abstractions which caused exceptions in U env. This PR consolidates the package to a single version.
* #510

fix: Microsoft.Extensions.Logging.Abstractions version issues

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Model/202108300923 Rename MP grid area id.sql

MeteringGridAreaId colunn renamed to GridAreaId as Metering prefix did not add any value
* #510

fix: wrong column name issue

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Charges/Charge.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/MeteringPoints/MeteringPoint.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/Model/ChargeOperation.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Factories/ChargeLinkFactoryTests.cs

To split #334 the unittests of ChargeLinkFactory are added in this PR
* #334

Add test of ChargeLinkFactory

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Factories/ChargeLinkFactoryTests.cs

Renamed from receivedEvent to actualChargeLink
and gives each Should() a new line
These was meant to be part of #559 but did not get pushed before merge with main
Part of #559 and #334
* #0000

refac: rename received and move Should

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.CreateLinkCommandReceiver/Program.cs

This PR will fix DI for the CreateLinkCommandReceiver function.
* #476

bug: ChargeLinkCommandFactory added to DI

---

README.md

This PR updates the PI objectives in the Domain Road Map section to match those of PI6.
Also, it was decided to remove the objectives of the recent PI's as it was not found relevant to keep.
* #0000

docs: Added PI6 objectives to Domain Road Map

---

.github/workflows/tfsec-analysis.yml

This is an experiment to see what `tfsec` code scan can help us with in terms of security regarding our infrastructure as code.
Find `tfsec` [here](https://github.com/Energinet-DataHub/geh-charges/security/code-scanning).
* #0000

Try adding terraform security check

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Repositories/ChargeRepository.cs

Remove duplicated include code
* #0000

refac: ChargeRepository.cs cleanup

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/ChargeLinkCommandAcceptedHandlerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/ChargeLinkCommandHandlerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/ChargeLinkEventPublishHandlerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/CreateLinkCommandEventHandlerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Handlers/ChargeCommandHandlerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Handlers/ChargeCommandReceivedEventHandlerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Handlers/ChargesMessageHandlerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/MeteringPoints/Handlers/MeteringPointCreatedHandlerTests.cs

Handler tests were left in the wrong location.
* #0000

Move handler tests to handler folder

---

.github/actions/infrastructure-cd/action.yml
.github/workflows/infrastructure-cd.yml

Use composite GitHub actions to remove a number of duplicated steps in infra CD pipeline.

Remove duplicated Github Action steps

---

.github/actions/infrastructure-cd/action.yml
.github/workflows/infrastructure-cd.yml

Fix infra CD pipeline

---

.github/actions/infrastructure-cd/action.yml
.github/workflows/infrastructure-cd.yml

Extract secret from action and move to input variables 
* #0000

fix: Remove use of secrets from shared action

---

source/GreenEnergyHub.Charges.Libraries/GreenEnergyHub.DataHub.Charges.Libraries.sln

After TestHelpers were added to the Charge.Libraries there were a missing dependency to TestCommon. This PR will add that dependency.
* #0000

Charges.Libraries add missing dependecy for TestCommon

---

.github/actions/dotnet-publish-nuget/action.yml

updated BRANCH variable in dotnet.publish-nuget

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Charges/MessageHub/ChargeDataAvailableNotifierEndpoint.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Common/EnvironmentSettingNames.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Program.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/EntityConfigurations/AvailableChargeDataConfiguration.cs

There was a configuration missing and a wrongly configured MessageExtractor
* #594

fix IoC errors and configuration for ChargeDataAvailableNotifierEndpoint

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/ChargeLinks/MessageHub/ChargeLinkBundleSenderEndpoint.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Common/EnvironmentSettingNames.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/SharedConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Health/HealthStatus.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeLinks/MessageHub/ChargeLinkDataAvailableNotifierEndpointTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/Charges/ChargeIngestionTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Fixtures/ChargesFunctionAppFixture.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Fixtures/ChargesFunctionAppServiceBusOptions.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestFiles/ValidCreateTariffCommand.xml

Add tests of published charge integration events.
Refactors - including splitting - existing domain tests.
This PR will be succeeded by new PRs covering:
- Use correlation ID to track whether e.g. published events correlate with the triggering command/event
- Optimize code in order to make test code shorter and more maintainable
* #716

Domain test charge integration events

---

.github/utilities/md-spellcheck/wordlist.txt
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md

Add missing package release notes.
* #588

Add missing package release notes

---

source/Energinet.Charges.Libraries/source/Directory.Build.props
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.IntegrationTests/Energinet.DataHub.Charges.Clients.IntegrationTests.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.SimpleInjector/Energinet.DataHub.Charges.Clients.SimpleInjector.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.SimpleInjector/documents/release-notes/release-notes.md
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.SimpleInjectorTests/Energinet.DataHub.Charges.Clients.SimpleInjectorTests.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/Energinet.DataHub.Charges.Clients.Tests.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md

Update libraries NuGet dependencies

---

build/infrastructure/main/func-functionhost.tf

The purpose of this PR is to enable always on on our functionhost.
* #0000

build: Enable always on

---

.github/workflows/ci.yml
.github/workflows/clients-ci.yml
.github/workflows/clients-simple-injector-ci.yml

Updating to Energinet-DataHub/.github/.github/workflows/dotnet-solution-ci.yml@2.2.0 effectively disables code cov.
See also [here](https://teams.microsoft.com/l/message/19:91c8a12a0ed34734b72b5678596377f5@thread.tacv2/1637926666672?tenantId=f7619355-6c67-4100-9a78-1847f30742e2&groupId=e1b7877a-ee7d-4505-a4b2-4989abc2d22a&parentMessageId=1637926666672&teamName=GreenForce&channelName=Developers&createdTime=1637926666672).
* #866

Disable malfunctioning code cov

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/GreenEnergyHub.Charges.Application.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/ChargeBundle/ChargeBundleCreator.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/ChargeLinkBundle/ChargeLinkBundleCreator.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/ChargeLinkReceiptBundle/ChargeLinkConfirmationBundleCreator.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/MessageHub/BundleCreatorProvider.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/GreenEnergyHub.Charges.IntegrationTests.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/MessageHubHelper.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/ChargeBundle/ChargeBundleCreatorTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/ChargeLinkBundle/ChargeLinkBundleCreatorTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/ChargeLinkReceiptBundle/ChargeLinkConfirmationBundleCreatorTests.cs

updated messageHub packages to newest versions

---

README.md

Code coverage has temporarily been deactivated due some strange results. While this is being investigated and fixed, the code cov badge on the repo front page (README) is out commented. 
* #0000

docs: Temporarily remove code-cov badge in repo README

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/Handlers/ChargeLinkDataAvailableNotifyAndReplyHandler.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/Handlers/ChargeLinkDataAvailableReplyHandler.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/Handlers/IChargeLinkDataAvailableNotifierAndReplyHandler.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/Handlers/IChargeLinkDataAvailableReplyHandler.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/MessageHub/ChargeLinkDataAvailableNotifier.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/ChargeLinks/MessageHub/ChargeLinkDataAvailableNotifierEndpoint.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/ChargeLinkDataAvailableNotifierConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/ChargeLinkDataAvailableNotifierAndReplyHandlerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/ChargeLinkDataAvailableReplyHandlerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/MessageHub/ChargeLinkDataAvailableNotifierTests.cs

Refactor the notifier to have a separate handler.
In an upcoming pull request the Notifier is made generic and #902 makes it hard to merge. 
* #0000

Create new handler for notify and reply

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/DbTypes.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/EntityConfigurations/AvailableChargeDataConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/EntityConfigurations/AvailableChargeLinkReceiptDataConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/EntityConfigurations/AvailableChargeLinksDataConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/EntityConfigurations/AvailableChargeReceiptDataConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/EntityConfigurations/ChargeEntityConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/EntityConfigurations/DefaultChargeLinkEntityConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Context/EntityConfigurations/MeteringPointEntityConfiguration.cs

More clean code and ensure that domain models and SQL models will stay more aligned.
* #628

Clean up EF Core configurations

---

source/Contracts/ChargeLink/ChargeLinkDto.cs
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md

As another solution is made for handling nullable properties when front end auto generates typscript files from swagger.json
* #976

Revert ChargeLinkDto to record

---

source/GreenEnergyHub.Charges/GreenEnergyHub.Charges.sln.DotSettings
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/Handlers/ChargeLinksDataAvailableNotifiedPublisher.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/Handlers/CreateDefaultChargeLinksReplyHandler.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/Handlers/CreateLinkRequestHandler.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/Handlers/IChargeLinksDataAvailableNotifiedPublisher.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/Handlers/ICreateDefaultChargeLinksReplyHandler.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/ChargeLinks/Handlers/ICreateLinkRequestHandler.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeLinksCommands/ChargeLinksCommandFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeLinksCommands/IChargeLinksCommandFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeLinksDataAvailableNotifiedEvents/ChargeLinksDataAvailableNotifiedEvent.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeLinksDataAvailableNotifiedEvents/ChargeLinksDataAvailableNotifiedEventFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeLinksDataAvailableNotifiedEvents/IChargeLinksDataAvailableNotifiedEventFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/CreateDefaultChargeLinksRequests/CreateDefaultChargeLinksRequest.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/ChargeLinks/CreateChargeLinkReceiverEndpoint.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/ChargeLinks/CreateDefaultChargeLinksReplierEndpoint.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/ChargeLinks/MessageHub/ChargeLinkDataAvailableNotifierEndpoint.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/ChargeLinkDataAvailableNotifierConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/DefaultChargeLinkEventReplierConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Contracts/External/ConsumptionMeteringPointCreated/ConsumptionMeteringPointCreatedInboundMapper.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Contracts/Public/CreateDefaultChargeLinks/CreateDefaultChargeLinksInboundMapper.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Contracts/Public/DefaultChargeLinksCreated/DefaultChargeLinksCreatedInboundMapper.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Contracts/Public/DefaultChargeLinksCreated/DefaultChargeLinksCreatedOutboundMapper.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/GreenEnergyHub.Charges.Infrastructure.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/ChargeLinkDataAvailableReplyHandlerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/CreateDefaultChargeLinksReplyHandlerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/CreateLinkRequestHandlerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeLinksCommands/ChargeLinksCommandFactoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Contracts/External/ConsumptionMeteringPointCreated/ConsumptionMeteringPointCreatedIntegrationInboundMapperTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/Contracts/Public/CreateDefaultChargeLinks/CreateDefaultChargeLinksInboundMapperTests.cs

Main improvement is that the message hub endpoint publishes
an event about that it has notified the Message Hub rather
that telling that charge links were created as that is no
business of the message hub stack.
Improve naming and file/folder structure
Main improvement is that the message hub endpoint publishes an event about that it has notified the Message Hub rather that  telling that charge links were created as that is no business of the message hub stack.
In particular, the infrastructure has undergone quite some refactoring for better maintainability:
* #946

Improve naming and file/folder structure

---

.github/CODEOWNERS

Updates codeowners to correct list.
* #0000

Update codeowners for charges

---

.github/dependabot.yml

Try to activate dependabot

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/CimDeserialization/ChargeBundle/ChargeCommandDeserializer.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Fixtures/Database/ChargesDatabaseFixture.cs

Remove irrelevant todos

---

.github/CODEOWNERS

As per [internal decision](https://teams.microsoft.com/l/message/19:91c8a12a0ed34734b72b5678596377f5@thread.tacv2/1641548085903?tenantId=f7619355-6c67-4100-9a78-1847f30742e2&groupId=e1b7877a-ee7d-4505-a4b2-4989abc2d22a&parentMessageId=1641548085903&teamName=GreenForce&channelName=Developers&createdTime=1641548085903).
* #0000

MightyDucks are no longer code owners of infra

---

.github/dependabot.yml

Higher frequency causes too much maintenance overhead.
* #868

Revert to monthly dependabot updates

---

source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.IntegrationTests/Energinet.DataHub.Charges.Clients.IntegrationTests.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/documents/release-notes/release-notes.md
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.RegistrationTests/Energinet.DataHub.Charges.Clients.RegistrationTests.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/Energinet.DataHub.Charges.Clients.Tests.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md

update packages in Charges.Libraries

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/SharedConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/GreenEnergyHub.Charges.FunctionHost.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Program.cs

removes logging temporarily
* #0000

removes logging temporarily

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/TestHelpers/EmbeddedResourceHelper.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/TestFiles/RequestChangeBillingMasterData.xml

This PR:
Changes values in test file used in upcoming system test - to ensure Status 200 OK is returned.
It is on purpose that the content of the test file will result in a rejection by the async validation.
* #951

Changing values in test file used in upcoming system test - to ensure Status 200 OK is returned, but the charge is rejected in async validation

---

build/infrastructure/main/func-functionhost.tf
build/infrastructure/main/locals.tf
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/System/HealthStatus.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/Fixtures/ChargesFunctionAppFixture.cs

Fix actor synchronization endpoint

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Helpers/CustomScriptProvider.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/Enumeration/ExactValueNameComparisonStrategy.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Core/Enumeration/IEnumValueNameComparisonStrategy.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Charges/ChargeFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/BusinessValidation/Factories/ChargeCommandBusinessValidationRulesFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/BusinessValidation/ValidationRules/CommandSenderMustBeAnExistingMarketParticipantRule.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeLinksCommands/Validation/InputValidation/Factories/ChargeLinksCommandInputValidationRulesFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/Validation/IInputValidationRulesFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/Validation/IInputValidator.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/MessagingExtensions/Registration/ProtobufOneOfConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Core/Json/JsonSerializerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/BusinessValidation/ValidationRules/CommandSenderMustBeAnExistingMarketParticipantRuleTests.cs

Fix some SonarQube warnings.
During this PR it turned out that there might be lots of warnings. Some are easy to fix, some require more work and yet some that we'd probably want to suppress. So this PR solely focuses on some of the easy fixes.
* #0000

Fix (some) SonarQube warnings

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeLinksCommands/ChargeLinksCommandFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/MarketParticipants/IMarketParticipantRepository.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Persistence/Repositories/MarketParticipantRepository.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/Repositories/MarketParticipantRepositoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeData/AvailableChargeDataFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeLinksData/AvailableChargeLinksDataFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableData/AvailableDataFactoryBase.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeLinksCommands/ChargeLinksCommandFactoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/BundleSpecification/ChargeLinks/ChargeLinksRejectionBundleSpecificationTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/BundleSpecification/Charges/ChargeRejectionBundleSpecificationTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Infrastructure/Cim/Bundles/ChargeLinks/ChargeLinkCimSerializerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Infrastructure/Cim/Bundles/ChargeLinksReceipt/ChargeLinkReceiptCimSerializerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Infrastructure/Cim/Bundles/ChargeReceipt/ChargeReceiptCimSerializerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Infrastructure/Cim/Bundles/Charges/ChargeCimSerializerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeData/AvailableChargeDataFactoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeLinkReceiptData/AvailableChargeLinkReceiptDataFactoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeLinksData/AvailableChargeLinksDataFactoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeReceiptData/AvailableChargeConfirmationDataFactoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeReceiptData/AvailableChargeRejectionDataFactoryTests.cs

A little clean up of the market participant repository

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/BusinessValidation/Factories/ChargeCommandBusinessValidationRulesFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/MessagingExtensions/MessageExtractor.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Persistence/Repositories/ChargeRepository.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Persistence/Repositories/MarketParticipantRepository.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/MessageHub/AvailableDataNotifier.cs
source/Shared/GreenEnergyHub/source/GreenEnergyHub.Json/JsonSerializer.cs

Inspired by the section "Consider using return Task instead of return await" of [this article](https://medium.com/@deep_blue_day/long-story-short-async-await-best-practices-in-net-1f39d7d84050).
* #926

Remove unnecessary async/await

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/MarketParticipants/MarketParticipant.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/ActorRegister/MarketParticipantsSynchronization/MarketParticipantUpdater.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/Reflection/ReflectionExtensions.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/ActorRegister/MarketParticipantUpdaterTests.cs

The temporary actor register solution apparently makes changes to the market participant id (identification number) of market participants. So we need this change in order to not break the synchronization in the charges domain.
* #926

Accept invalid actor updates from actor register

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/GreenEnergyHub.Charges.ApplyDBMigrationsApp.csproj

Remember to make dbup script embedded resource 😒 
* #0000

fix - set dbup script as embedded resource (OriginalOperationId length change)

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/SharedConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Program.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/MessagingExtensions/Factories/ServiceBusMessageFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure.Core/MessagingExtensions/ServiceBusChannelTests.cs

Temporarily remove action authentication because it deadlocks the actor test env.
* #1105

Temporarily remove action authentication

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/BusinessValidation/ValidationRules/ChargeUpdateNotYetSupportedRule.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeLinksCommands/Validation/BusinessValidation/ValidationRules/ChargeLinksUpdateNotYetSupportedRule.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/Validation/ValidationRuleIdentifier.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Cim/ValidationErrors/CimValidationErrorTextTemplateMessages.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/Shared/CimValidationErrorCodeFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeLinkReceiptData/ChargeLinksCimValidationErrorTextFactoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/Shared/CimValidationErrorCodeFactoryTests.cs

This pull request adds a specific error text for ChargeLinks updates.
* #938

ChargeLinks update not yet supported specific error text

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Seed/202201261740 Add default charges owner.sql

System operator has a new ID in Market Participant registry.
We update our representation of the system operator accordingly.

Update system operator id in Charges db

---

.github/CODEOWNERS

Jan Duelund @x-platformcoder is a new team member of Team Volt

Add Jan Duelund as codeowner

---

docs/local-development/run-integration-tests-local.md
wordlist.txt

Setup of prerequisites for running integration tests in the charges domain is well documented in the geh-core repository. This pull request replaces the description in the charges domain with a link to the description in geh-core.

Link to TestCommon integration test setup guide

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/GreenEnergyHub.Charges.ApplyDBMigrationsApp.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Model/202203090952 Add DocumentType to AvailableData.sql
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/GreenEnergyHub.Charges.IntegrationTest.Core.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/GreenEnergyHub.Charges.IntegrationTests.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/Repositories/RepositoryAutoMoqDataFixer.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/GreenEnergyHub.Charges.MessageHub.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Infrastructure/Persistence/EntityConfigurations/AvailableChargeDataConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Infrastructure/Persistence/EntityConfigurations/AvailableChargeLinkReceiptDataConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Infrastructure/Persistence/EntityConfigurations/AvailableChargeLinksDataConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Infrastructure/Persistence/EntityConfigurations/AvailableChargeReceiptDataConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/MessageHub/AvailableDataNotificationFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeData/AvailableChargeData.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeData/AvailableChargeDataFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeLinksData/AvailableChargeLinksData.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeLinksData/AvailableChargeLinksDataFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeLinksReceiptData/AvailableChargeLinksReceiptData.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeLinksReceiptData/AvailableChargeLinksReceiptDataFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeLinksReceiptData/AvailableChargeLinksRejectionDataFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeReceiptData/AvailableChargeConfirmationDataFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeReceiptData/AvailableChargeReceiptData.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeReceiptData/AvailableChargeRejectionDataFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableData/AvailableDataBase.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Builders/MessageHub/AvailableChargeDataBuilder.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/BundleSpecification/ChargeLinks/ChargeLinksRejectionBundleSpecificationTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/BundleSpecification/Charges/ChargeRejectionBundleSpecificationTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Infrastructure/Cim/Bundles/ChargeLinks/ChargeLinkCimSerializerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Infrastructure/Cim/Bundles/ChargeLinksReceipt/ChargeLinkReceiptCimSerializerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Infrastructure/Cim/Bundles/ChargeReceipt/ChargeReceiptCimSerializerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Infrastructure/Cim/Bundles/Charges/ChargeCimSerializerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/MessageHub/AvailableDataNotificationFactoryTests.cs

Added the cim document type to the message that is delivered to the messagehub after request is validated and stored
* #1185

1185 response header must contain message type

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Handlers/ChargeCommandReceivedEventHandler.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Charges/Charge.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Charges/OperationType.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Handlers/ChargeCommandReceivedEventHandlerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Builders/Command/ChargeCommandBuilder.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Charges/ChargeTests.cs

Added handling of cancel stop event.
* #0000

1152 cancel stop charge

---

source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.IntegrationTests/Energinet.DataHub.Charges.Clients.IntegrationTests.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/GreenEnergyHub.Charges.Infrastructure.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/GreenEnergyHub.Charges.IntegrationTest.Core.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/GreenEnergyHub.Charges.IntegrationTests.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/GreenEnergyHub.Charges.SystemTests.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/GreenEnergyHub.Charges.TestCore.csproj

Energinet.DataHub.Core NuGet packages are updated.

Update geh-core NuGet packages

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Infrastructure/Cim/CimSerializer.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/TestFiles/ExpectedOutputChargeCimSerializerMasterDataAndPrices.blob
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/TestFiles/ExpectedOutputChargeCimSerializerMasterDataWithoutPrices.blob
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/TestFiles/ExpectedOutputChargeCimSerializerPricesWithoutMasterData.blob
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/TestFiles/ExpectedOutputChargeLinkCimSerializer.blob
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/TestFiles/ExpectedOutputChargeLinkReceiptCimSerializerConfirmation.blob
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/TestFiles/ExpectedOutputChargeLinkReceiptCimSerializerRejection.blob
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/TestFiles/ExpectedOutputChargeReceiptCimSerializerConfirmation.blob
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/TestFiles/ExpectedOutputChargeReceiptCimSerializerRejection.blob

Charges messages sent to market participants failed schema validation.
This PR provides a solution for that problem.
Issue submitter has had a look at the proposed solution and given it a 👍 .
https://github.com/Energinet-DataHub/green-energy-hub/issues/284

Fix: Resolve schema validation problem - 284

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestFiles/Charges/Samples/FeeMonthlyPriceSample.xml
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestFiles/Charges/Samples/SubscriptionMonthlyPriceSample.xml
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestFiles/Charges/Samples/TariffHourlyPricesSample.xml

Remove xsi headers in sample files as agreed on with software architecht and product owner.
* [GEH Incident #284](https://app.zenhub.com/workspaces/team-volt-60a61059028fd7000e49956e/issues/energinet-datahub/green-energy-hub/284)

Remove xsi headers in sample files

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/GreenEnergyHub.Charges.ApplyDBMigrationsApp.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Seed/202203251356 Alter default charges.sql

Some charge names and descriptions were persisted to the charges database using special characters.
These texts are updated using correct danish characters.
* #1225

Update texts containing danish characters

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/GreenEnergyHub.Charges.ApplyDBMigrationsApp.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Model/280320221347 Add unique constraint on Charge Link.sql

This removes all duplicate charge links then adds
2 unique constraints to avoid future duplicate rows
When charge link history is added this might need
to be changed depending on implementation
* #1209

feat: add unique constraints to charge links

---

.github/CODEOWNERS

@jonasdmoeller is added as codeowner

Add @jonasdmoeller as codeowner

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Persistence/Repositories/RulesConfigurationRepository.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/Repositories/RulesConfigurationRepositoryTests.cs

Configuration of StartDateValidation is changed to allow charge requests from 720 days back in time.
* #1121

Allow charge requests from 720 days back in time

---

docs/business-processes/validations.md
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/BusinessProcessTests.cs

Test: Temporarily changing system test assert to it will fail when executed in CD pipeline - testing deployment guard
* #951

Test: Temporarily changing system test assert so it will fail when executed in CD pipeline - testing deployment guard

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/BusinessProcessTests.cs

Reverting this [PR](https://github.com/Energinet-DataHub/geh-charges/pull/1263), so the system test will pass again.
* 951

Test: Reverting the system test which was temporarily set to fail in CD pipeline

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/GreenEnergyHub.Charges.FunctionHost.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Program.cs

logging middleware upgrade to 1.2.0
* #0000

logging middleware upgrade to 1.2.0

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/GreenEnergyHub.Charges.FunctionHost.csproj

request response logging upgrade 1.2.1
* #0000

upgradede loggin middleware

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/ApiManagementTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/BusinessProcessTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/Fixtures/SystemTestCollectionFixture.cs

Currently our System Test execution fails due to parallel execution. This PR adds `SystemTestCollectionFixture` which is applied on our System test classes to ensure tests are executed sequentially.
* #0000

fix: run system tests sequentially to avoid parallel test execution causing tests to fail

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/BusinessProcessTests.cs

This PR fixes a mistake in the system test's expected MessageType HTTP header value.
* Incident 169

Test: fix system test to expect the correct MessageType HTTP header value

---

source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/documents/release-notes/release-notes.md
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md

This pull request bumps version for the Charges.Clients and Charges.Clients.Registration NuGet packages as we should have done in [pull request 1332](https://github.com/Energinet-DataHub/geh-charges/pull/1332).
* #1332

Bump Charges Clients and Registration version

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Charges/ChargeIngestion.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/GreenEnergyHub.Charges.IntegrationTest.Core.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestFiles/Charges/ChargeDocument.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestFiles/Charges/PriceSeries/TariffPriceSeriesWithInvalidBusinessReasonCode.xml
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeIngestionTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeLinkIngestionTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/BusinessProcessTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/MyDomainTests.cs

Sender validation hid schemavalidation errors
which was triggered as sender is not set when
schema validation fails
* #1339

1339 syncronous validation fix

---

README.md

This PR (re)adds the CodeCov badge showing the measured code coverage percentage.
* #0000

Repo: Add CodeCov badge to Charges repo

---

README.md

This PR replaces previous domain road map goals with the current ones.
* #0000

Docs: Update domain road map

---

docs/business-processes/settlement-master-data.md

This PR updates the Settlement Master Data process description as per SME review comments.
* #325

Docs: Update Settlement Master Data process description

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestFiles/Charges/CreateSubscriptionDocument.xml
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestHelpers/EmbeddedResourceHelper.cs

This PR fixes the test data provided in the file `CreateSubscriptionDocument.xml`, so it no longer violates this validation rule `NumberOfPointsMatchTimeIntervalAndResolution`
* #1294

Fix: System test failing after introducing validation rule `NumberOfPointsMatchTimeIntervalAndResolution`

---

build/infrastructure/main/func-functionhost.tf
build/infrastructure/main/sbt-price-command-received.tf
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Handlers/ChargeCommandHandler.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargePriceCommandReceivedEvents/ChargePriceCommandReceivedEvent.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Charges/ChargePriceCommandReceiverEndpoint.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Common/EnvironmentSettingNames.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/ChargeIngestionConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/ChargePriceCommandReceiverConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Program.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/local.settings.sample.json
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/Fixtures/FunctionApp/ChargesFunctionAppFixture.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/Fixtures/FunctionApp/ChargesServiceBusResourceNames.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeIngestionTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/Repositories/MarketParticipantRepositoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/ChargeLinks/Handlers/ChargeLinkEventPublishHandlerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Acknowledgement/ChargeCommandConfirmationServiceTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/MessageHub/AvailableDataNotificationFactoryTests.cs

This is the first of multiple pull requests covering [issue 1409](https://app.zenhub.com/workspaces/team-volt-60a61059028fd7000e49956e/issues/energinet-datahub/geh-charges/1409).
With this we solve the following tasks:
Upcoming tasks:
* #1409

feat: 1409 new price flow #1 introduce price infrastructure

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Model/202205181253 Add actorId to availabledata.sql
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Test/202201261750 Add test data.sql
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/MarketParticipants/MarketParticipant.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestFiles/ChargeLinks/TaxTariffWithCreateAndUpdateDueToOverLappingPeriodChargeLinkDocument.xml
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestFiles/Charges/PriceSeries/TariffPriceSeries.xml
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestHelpers/MessageHubHelper.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeIngestionTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeLinkIngestionTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/CreateDefaultChargeLinksReceiverTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/Repositories/AvailableDataRepositoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/Repositories/ChargeRepositoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/Repositories/MarketParticipantRepositoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/Repositories/RepositoryAutoMoqDataFixer.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/SeededData.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeLinksReceiptData/AvailableChargeLinksReceiptDataFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeLinksReceiptData/AvailableChargeLinksRejectionDataFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeReceiptData/AvailableChargeReceiptDataFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeReceiptData/AvailableChargeRejectionDataFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableData/AvailableDataFactoryBase.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Builders/MessageHub/AvailableChargeDataBuilder.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeLinkReceiptData/AvailableChargeLinkReceiptDataFactoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeLinkReceiptData/AvailableChargeLinkRejectionDataFactoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeReceiptData/AvailableChargeConfirmationDataFactoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeReceiptData/AvailableChargeRejectionDataFactoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/Shared/MarketParticipantRepositoryMockBuilder.cs

Adds actorId to availabledata tables, inserting id from marketparticipant in newly inserted field, if marketparticipant does not exist an empty guid is inserted
* #1345

fix: dead available data is populated with SYO Id

---

docs/business-processes/asynchronous-validations.md
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/InputValidation/Factories/ChargeOperationInputValidationRulesFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/InputValidation/ValidationRules/TerminationDateMustMatchEffectiveDateValidationRule.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/Validation/ValidationRuleIdentifier.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Cim/ValidationErrors/CimValidationErrorTextTemplateMessages.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/Shared/CimValidationErrorCodeFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Builders/Command/ChargeOperationDtoBuilder.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/InputValidation/ChargeOperationInputValidationRulesFactoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/InputValidation/ValidationRules/TerminationDateMustMatchEffectiveDateValidationRuleTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/Shared/CimValidationErrorCodeFactoryTests.cs

When termination date (EndDate) is set it must be the same
as effective date (StartDate)
* #1326

feat: add termination date validation rule

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Cim/ValidationErrors/CimValidationErrorTextTemplateMessages.cs

Additional error text changes as per request by our SME.
This PR changes error texts for 
`ChargeIdRequiredValidationRule`
`ChargeIdLengthValidation`
* #0000

Fix: Changes additional validation rule error texts

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/MarketParticipants/Handlers/MarketParticipantEventHandler.cs

Adds logging that shows the type of integration events received from Market Participant domain.
* #1345

Debug: Log the type of integration events received from Market Participant domain

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/MarketParticipants/Handlers/MarketParticipantEventHandler.cs

Changes log level and texts.
* #1345

Debug: change log level and log text (for Market Participant integration event receival)

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/Cim/ValidationErrors/CimValidationErrorTextTemplateMessages.cs

This PR changes a couple of validation error texts as per SME request.
* #0000

Fix: Changed validation texts for Name and Description rules

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Handlers/ChargeInformationCommandReceivedEventHandler.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Handlers/ChargePriceEventHandlerDeprecated.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Handlers/IChargePriceEventHandlerDeprecated.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/ChargeCommandReceiverConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeIngestionTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Handlers/ChargeCommandReceivedEventHandlerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Handlers/ChargePriceEventHandlerDeprecatedTests.cs

By mistake the previous PR broke D08 workflow
This PR reimplements this until the new D08 workflow is fully functional
* #1410

fix: reenable old flow

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/GreenEnergyHub.Charges.ApplyDBMigrationsApp.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Model/202207271035 Remove position from ChargePoint.sql
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Charges/PointExtensions.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/ChargeOperationDto.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/ChargePriceMaximumDigitsAndDecimalsRule.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeInformationCommands/Validation/InputValidation/ValidationRules/MaximumPriceRule.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargePriceCommands/Validation/InputValidation/ValidationRules/MaximumPriceRule.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/CimDeserialization/ChargeBundle/ChargeCommandBundleConverter.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Persistence/EntityConfigurations/ChargeEntityConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeData/AvailableChargeDataFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.MessageHub/Models/AvailableChargeReceiptData/ChargeCimValidationErrorTextFactory.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Model/ChargePoint.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Handlers/ChargePriceEventHandlerDeprecatedTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/Charges/Handlers/ChargePriceEventHandlerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Builders/Command/ChargeOperationDtoBuilder.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Builders/Command/ChargePriceOperationDtoBuilder.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Builders/Command/PointBuilder.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Charges/ChargeTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/InputValidation/ChargeOperationInputValidationRulesFactoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/InputValidation/ValidationRules/ChargePriceMaximumDigitsAndDecimalsRuleTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/InputValidation/ValidationRules/MaximumPriceRuleTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargePriceCommands/Validation/InputValidation/ChargePriceOperationInputValidationRulesFactoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargePriceCommands/Validation/InputValidation/ValidationRules/MaximumPriceRuleTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure/CimDeserialization/ChargeBundle/ChargeCommandBundleConverterTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeData/AvailableChargeDataFactoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Models/AvailableChargeReceiptData/ChargeCimValidationErrorTextFactoryTests.cs

When we need it, we calculate it instead
* #1411

feat: remove position from charge point

---

.github/CODEOWNERS

Added Morten (ShaBloze) to codeowners

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Services/ChargePriceConfirmationService.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Services/ChargePriceNotificationService.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/Charges/Services/ChargePriceRejectionService.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/MarketParticipants/Handlers/MarketParticipantEventHandler.cs

This PR
* adds additional logging to verify story 1208
* fixes existing logs that did not follow the logging template (not related to 1208)
* #1208

Log: Add additional logging for story 1208 and fixing log entries not following log template

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestHelpers/MessageHubHelper.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeIngestionTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeLinkIngestionTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/CreateDefaultChargeLinksReceiverTests.cs

Use AssertionScope to improve error handling in integration tests.

fix: Improve error handling in tests involving MessageHub

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/GreenEnergyHub.Charges.Application.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/GreenEnergyHub.Charges.FunctionHost.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/GreenEnergyHub.Charges.Infrastructure.Core.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestHelpers/HttpRequestGenerator.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/GreenEnergyHub.Charges.TestCore.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.WebApi/GreenEnergyHub.Charges.WebApi.csproj

Update Charges to use package "Energinet.Datahub.Core.App.FunctionApp" and depended packages to version 6.0.0
* #1559

fix: FunctionApp package etc. is upgraded to 6.0.0

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/GreenEnergyHub.Charges.Application.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/GreenEnergyHub.Charges.FunctionHost.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/GreenEnergyHub.Charges.Infrastructure.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/EndpointTests/GridAreaLinkPersisterEndPointTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/EndpointTests/MarketParticipantPersisterEndpointTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/GreenEnergyHub.Charges.Tests.csproj

The MarketParticipant domain has updated their `Energinet.DataHub.MarketParticipant.Integration.Model` NuGet package, and the production system is reliant on consuming domains to use the new package.
* #1579

chore: Update Energinet.DataHub.MarketParticipant.Integration.Model

---

build/infrastructure/main/kv-shared-resources.tf
build/infrastructure/main/mssqldb-this.tf

Move the SQL database into the SQL Server elastic pool.
This will not require backup, as no data is lost

move database to elastic pool

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/Builders/Command/ChargeInformationOperationDtoBuilder.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/ChargeCommands/Validation/InputValidation/ChargeOperationInputValidationRulesFactoryTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/Dtos/Messages/Events/DomainEventTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/FunctionHost/EnvironmentSettingNamesTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Infrastructure.Core/InternalMessaging/ChargeServiceBusResourceNamesTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/TestHelpers/CodeToInfrastructureCoherenceErrorMessageBuilder.cs

This pull request is an improvement to error messaging for missing Code to Infrastructure-as-Code coherence, which was introduced with pull request #1660.
* #1651

test: Improve error messaging for missing Code to Infrastructure-as-Code coherence

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Infrastructure/Cim/Bundles/ChargeLinks/ChargeLinkCimSerializerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Infrastructure/Cim/Bundles/ChargeLinksReceipt/ChargeLinkReceiptCimSerializerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Infrastructure/Cim/Bundles/ChargeReceipt/ChargeReceiptCimSerializerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Infrastructure/Cim/Bundles/Charges/ChargeCimSerializerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/MessageHub/Infrastructure/Cim/Bundles/Charges/ChargePriceCimSerializerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/TestHelpers/FilePathHelper.cs

This PR adds the full file path to the test files used in a few unit tests. 
* #0000

Test: Use full file paths

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestHelpers/EmbeddedResourceHelper.cs

This tries to make a cleaner way to avoid hitting the dates where we have either 23 or 25 hours.
* #1706

refac: make a cleaner way to avoid problems with summer winter time

---

.github/workflows/cd.yml

merge workflows introduced in pr #1721

---

source/Contracts/Charge/SearchCriteriaV1Dto.cs
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/documents/release-notes/release-notes.md
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/Charges/ChargesClientTests.cs
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Charges/ChargesClient.cs
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Charges/IChargesClient.cs
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/QueryServices/ChargesQueryServiceTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/V1/ChargesControllerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/GreenEnergyHub.Charges.QueryApi.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/QueryServices/ChargesQueryService.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/QueryServices/IChargesQueryService.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/Validation/SearchCriteriaValidator.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.TestCore/Builders/Query/SearchCriteriaDtoBuilder.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/WebApi/Validation/SearchCriteriaValidatorTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.WebApi/Controllers/V1/ChargesController.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.WebApi/Properties/launchSettings.json
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.WebApi/Startup.cs

Adjusting QueryService to handle if charge types is null.
Also added versioning to Search Criteria dto.
* #1656

fix: Adjusted search criteria for Web Api

---

.github/workflows/cd.yml
.github/workflows/charges-libraries-publish.yml
.github/workflows/ci.yml
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/documents/release-notes/release-notes.md
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj
source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md
wordlist.txt

We use environment AzureAuth to authenticate using oidc
* #0000

Authenticate using OIDC

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/MarketParticipants/Handlers/MarketParticipantDomainEventMapper.cs

fix: set b2c actor id to null on mp create

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeIngestionTestsChargeInformation.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeIngestionTestsChargePrices.cs

Secure correct ordering of operations in integration tests
* #1735

test: Assert correct ordering

---

build/infrastructure/main/sbs-integration-events.tf
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/local.settings.sample.json
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/InternalMessaging/ChargesServiceBusResourceNames.cs

Market participant external id changed too long name bug is fixed
* #1727

fix: Market participant external id changed too long name bug is fixed

---

source/Contracts/Charge/ChargeV1Dto.cs
source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj
source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/documents/release-notes/release-notes.md
source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj
source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/ModelPredicates/ChargeQueryLogic.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/WebApi/ModelPredicates/ChargeQueryLogicTests.cs

Add Charge Id to ChargeV1Dto. It is needed when searching for ChargePoints.
* #1688

feat: Add Charge Id to ChargeV1Dto

---

build/infrastructure/main/func-functionhost.tf
build/infrastructure/main/sbs-integration-events.tf
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/MarketParticipants/Handlers/IMarketParticipantNameChangedCommandHandler.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/MarketParticipants/Handlers/Mappers/MarketParticipantIntegrationEventMapper.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Application/MarketParticipants/Handlers/MarketParticipantNameChangedCommandHandler.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/Events/MarketParticipantNameChangedCommand.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/MarketParticipants/MarketParticipant.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Common/EnvironmentSettingNames.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/HealthCheckConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/IntegrationEventHandlersConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/MarketParticipant/MarketParticipantNameChangedEndpoint.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/local.settings.sample.json
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/InternalMessaging/ChargesServiceBusResourceNames.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/Fixtures/FunctionApp/ChargesFunctionAppFixture.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/EndpointTests/MarketParticipantNameChangedEndpointTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Application/MarketParticipants/Handlers/MarketParticipantIntegrationEventMapperTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/Domain/MarketParticipants/MarketParticipantTests.cs

This changes the name of the Market Participant based on the received event
* #1732

feat: add consume ActorNameChanged event

---

source/Contracts/Charge/ChargeV1Dto.cs
source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj
source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/documents/release-notes/release-notes.md
source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj
source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/ModelPredicates/ChargeQueryLogic.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Tests/WebApi/ModelPredicates/ChargeQueryLogicTests.cs

Added HasAnyPrices to ChargeV1Dto.
* #1688

feat: 1688 added hasAnyPrices to ChargeV1Dto

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/V1/ChargePricesControllerTests.cs

Fixed failing unit test

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Common/EnvironmentSettingNames.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Configuration/HealthCheckConfiguration.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/local.settings.sample.json
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure.Core/InternalMessaging/ChargesServiceBusResourceNames.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/Fixtures/FunctionApp/ChargesFunctionAppFixture.cs

Health check of removed endpoint

---

source/Contracts/ChargeMessage/ChargeMessagesV1Dto.cs
source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/Energinet.DataHub.Charges.Clients.Registration.csproj
source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Registration/documents/release-notes/release-notes.md
source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients.Tests/Charges/ChargesClientTests.cs
source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Charges/ChargesClient.cs
source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Charges/IChargesClient.cs
source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/Energinet.DataHub.Charges.Clients.csproj
source/Energinet.DataHub.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/QueryServices/ChargeMessagesQueryServiceTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/IntegrationTests/WebApi/V1/ChargeMessagesControllerTests.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/GreenEnergyHub.Charges.QueryApi.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/QueryServices/ChargeMessageQueryService.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.QueryApi/QueryServices/IChargeMessageQueryService.cs

To enable pagination in the frontend view of messages, we return an object with total count and the relevant messages.
* #1689

feat: Return ChargeMessagesV1Dto with total count and content

---

.github/workflows/cd.yml
.github/workflows/detect-changes.yml

Remove repository prefix from event name.
Ignore NuGet package folders in detect changes.

Change event type

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/local.settings.sample.json

Sample file was out of date and have not been updated when the new SB subscription prefix naming took effect

fix: will update sample file with new sub names

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/GreenEnergyHub.Charges.ApplyDBMigrationsApp.csproj
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Model/202211221157 Create Charge History Table.sql

New table to store all historic operations for a charge
* #1846

feat: charge history table

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.FunctionHost/Charges/ChargeIngestion.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/CimDeserialization/ChargeBundle/ChargeCommandBundleConverter.cs
source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/CimDeserialization/MarketDocument/DocumentConverter.cs

Bug fixed so schema validations are catched correctly and 
* #1070

fix: cim conversion errors result in schema, B2B sync or async errors

---

source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.SystemTests/GreenEnergyHub.Charges.SystemTests.csproj

Undo a change to a project file, which was not intended.

Remove file dependency
